@startuml
hide empty description

skinparam state {
  BackgroundColor<<pseudo>> LightGray
  BackgroundColor<<composite>> LightBlue
  BorderColor<<pseudo>> Gray
  FontStyle<<pseudo>> italic
}

legend top left
|= Variable |= Type |= Initial Value |
| counter | int | 0 |
endlegend

state "Root" as root <<composite>> {
    state "A" as root__a
    state "B" as root__b
    [*] --> root__a
    root__a --> root__b : A.Go
}
[*] --> root
root --> [*]
@enduml