@startuml
hide empty description

skinparam state {
  BackgroundColor<<pseudo>> LightGray
  BackgroundColor<<composite>> LightBlue
  BorderColor<<pseudo>> Gray
  FontStyle<<pseudo>> italic
}

legend top left
|= Variable |= Type |= Initial Value |
| counter | int | 0 |
endlegend

state "Root" as root <<composite>> {
    state "A" as root__a
    state "B" as root__b <<composite>> {
        state "B1" as root__b__b1
        state "B2" as root__b__b2
        [*] --> root__b__b1
        root__b__b1 --> root__b__b2 : B1.Next
    }
    [*] --> root__a
    root__a --> root__b : A.GoB
}
[*] --> root
root --> [*]
@enduml