import assert from 'node:assert/strict';
import * as path from 'node:path';

import {
    createDocument,
    packageModule,
    trackTempDir,
    writeFile,
} from './support';

describe('jsfcstm diagram preview', () => {
    afterEach(() => {
        packageModule.getWorkspaceGraph().clearOverlays();
    });

    const zeroRange = {
        start: {line: 0, character: 0},
        end: {line: 0, character: 0},
    };

    it('builds diagram IR with hierarchy, shared-event coloring, and transition semantics', async () => {
        const document = createDocument([
            'def int counter = 0;',
            'state TrafficLight {',
            '    event Tick named "Cycle";',
            '    enter Setup {',
            '        counter = 0;',
            '    }',
            '    state Idle;',
            '    state Running;',
            '    state Done;',
            '    [*] -> Idle;',
            '    Idle -> Running : Tick effect {',
            '        counter = counter + 1;',
            '    };',
            '    Running -> Done : Tick;',
            '    Done -> [*] : if [counter > 0];',
            '}',
        ].join('\n'), '/tmp/diagram-model.fcstm');

        const ast = await packageModule.parseAstDocument(document);
        const model = packageModule.buildStateMachineModel(ast);
        const diagram = packageModule.buildFcstmDiagramFromStateMachine(model);

        assert.ok(diagram);
        assert.equal(diagram!.machineName, 'TrafficLight');
        assert.deepEqual(diagram!.summary, {
            variables: 1,
            states: 4,
            events: 1,
            transitions: 4,
            actions: 1,
        });
        assert.equal(diagram!.variables[0].name, 'counter');
        assert.equal(diagram!.rootState.children.length, 3);
        assert.equal(diagram!.rootState.events[0].qualifiedName, 'TrafficLight.Tick');
        assert.equal(diagram!.rootState.actions[0].label, 'enter Setup');
        assert.equal(diagram!.eventLegend.length, 1);
        assert.equal(diagram!.eventLegend[0].qualifiedName, 'TrafficLight.Tick');
        assert.equal(diagram!.eventLegend[0].label, 'Cycle (Tick)');
        assert.equal(diagram!.eventLegend[0].transitionCount, 2);
        assert.equal(diagram!.rootState.transitions[1].triggerLabel, 'Cycle (Tick)');
        assert.equal(diagram!.rootState.transitions[1].label, 'Idle -> Running Cycle (Tick) effect');
        assert.deepEqual(diagram!.rootState.transitions[1].effectLines, [
            'effect {',
            '    counter=counter+1;',
            '}',
        ]);
        assert.equal(diagram!.rootState.transitions[1].eventColor, diagram!.rootState.transitions[2].eventColor);
        assert.ok(diagram!.rootState.transitions[1].eventColor);
        assert.equal(diagram!.rootState.transitions[3].guardLabel, 'counter>0');
    });

    it('renders Mermaid statechart source with state details and transition labels', async () => {
        const document = createDocument([
            'def int counter = 0;',
            'state Root named "Root <Main>" {',
            '    event Start named "Go & Run";',
            '    state Idle;',
            '    state Running;',
            '    [*] -> Idle;',
            '    Idle -> Running : Start effect {',
            '        counter = counter + 1;',
            '    };',
            '    Running -> [*] : Start;',
            '}',
        ].join('\n'), '/tmp/diagram-svg.fcstm');

        const ast = await packageModule.parseAstDocument(document);
        const model = packageModule.buildStateMachineModel(ast);
        const diagram = packageModule.buildFcstmDiagramFromStateMachine(model);
        const mermaid = await packageModule.renderFcstmDiagramMermaid(diagram!);
        const renderResult = await packageModule.renderFcstmDiagramMermaidView(diagram!);
        const effectNotes = packageModule.collectFcstmDiagramEffectNotes(diagram!);

        assert.match(mermaid, /^%% FCSTM Mermaid preview generated by jsfcstm/m);
        assert.match(mermaid, /^stateDiagram-v2$/m);
        assert.match(mermaid, /^direction TB$/m);
        assert.doesNotMatch(mermaid, /state "Root <Main> \(Root\) \[1e\/2s\]" as state_\d+ \{/);
        assert.match(mermaid, /state "Idle" as state_\d+/);
        assert.match(mermaid, /\[\*\] --> state_\d+/);
        assert.match(mermaid, /state_\d+ --> state_\d+ : Go & Run \(Start\)/);
        assert.match(mermaid, /state_\d+ --> \[\*\] : Go & Run \(Start\)/);
        assert.doesNotMatch(mermaid, /event Go & Run/);
        assert.equal(renderResult.renderedTransitions.length, 3);
        assert.equal(effectNotes.length, 1);
        assert.match(effectNotes[0].effectText, /^effect \{\n    counter=counter\+1;\n\}$/m);
        assert.doesNotMatch(mermaid, /<svg/i);
    });

    it('resolves preview detail levels and effect-note formatting with pyfcstm-style controls', async () => {
        const document = createDocument([
            'def int counter = 0;',
            'state Root {',
            '    event Start named "Go & Run";',
            '    state Idle;',
            '    state Running;',
            '    [*] -> Idle;',
            '    Idle -> Running : Start effect {',
            '        if [counter > 0] {',
            '            counter = counter + 1;',
            '        } else {',
            '            counter = 0;',
            '        }',
            '    };',
            '}',
        ].join('\n'), '/tmp/diagram-options.fcstm');

        const ast = await packageModule.parseAstDocument(document);
        const model = packageModule.buildStateMachineModel(ast);
        const diagram = packageModule.buildFcstmDiagramFromStateMachine(model);
        const minimal = packageModule.resolveFcstmDiagramPreviewOptions('minimal');
        const full = packageModule.resolveFcstmDiagramPreviewOptions({
            detailLevel: 'full',
            showEvents: false,
            showStateActions: false,
        });
        const inlineMermaid = await packageModule.renderFcstmDiagramMermaid(diagram!, {
            detailLevel: 'minimal',
            transitionEffectMode: 'inline',
        });
        const hiddenMermaid = await packageModule.renderFcstmDiagramMermaid(diagram!, {
            detailLevel: 'full',
            showEvents: false,
            transitionEffectMode: 'hide',
        });
        const noteEffects = packageModule.collectFcstmDiagramEffectNotes(diagram!, {
            detailLevel: 'full',
            transitionEffectMode: 'note',
        });

        assert.equal(minimal.transitionEffectMode, 'inline');
        assert.equal(minimal.showStateEvents, false);
        assert.equal(full.showEvents, false);
        assert.equal(full.showStateActions, false);
        assert.match(inlineMermaid, /Go & Run \(Start\) \/ if \[counter>0\] \{ counter=counter\+1,/);
        assert.match(inlineMermaid, /else \{ counter=0,/);
        assert.doesNotMatch(hiddenMermaid, /Go & Run \(Start\)/);
        assert.equal(noteEffects.length, 1);
        assert.equal(noteEffects[0].title, 'Idle -> Running');
        assert.equal(noteEffects[0].meta, 'Go & Run (Start)');
        assert.match(noteEffects[0].effectText, /^effect \{\n    if \[counter>0\] \{\n        counter=counter\+1;\n    \}\n    else \{\n        counter=0;\n    \}\n\}$/m);
    });

    it('covers builder fallbacks for null models, missing legend lookups, forced labels, and empty effect bodies', () => {
        assert.equal(packageModule.buildFcstmDiagramFromStateMachine(null), null);

        const repeatedEvent = {
            name: 'Missing',
            pathName: 'Root.Missing',
            extraName: undefined,
            declared: false,
            origins: ['chain'],
            statePath: ['Elsewhere'],
            path: ['Root', 'Missing'],
            range: zeroRange,
        };
        const singleEvent = {
            name: 'Solo',
            pathName: 'Root.Solo',
            extraName: undefined,
            declared: false,
            origins: ['absolute'],
            statePath: ['Root'],
            path: ['Root', 'Solo'],
            range: zeroRange,
        };
        const enterRefAction = {
            name: undefined,
            statePath: ['Root', null],
            stage: 'enter',
            aspect: undefined,
            mode: 'ref',
            is_abstract: false,
            is_ref: true,
            is_aspect: false,
            operations: [],
            funcName: 'FallbackFunc',
            refStatePath: ['Root', 'Shared'],
            refTargetQualifiedName: undefined,
            range: zeroRange,
        };
        const emptyDuringAction = {
            name: undefined,
            statePath: ['Root'],
            stage: 'during',
            aspect: undefined,
            mode: 'operations',
            is_abstract: false,
            is_ref: false,
            is_aspect: false,
            operations: [],
            funcName: 'Root.during',
            refStatePath: undefined,
            refTargetQualifiedName: undefined,
            range: zeroRange,
        };
        const aspectAction = {
            name: undefined,
            statePath: ['Root'],
            stage: 'during',
            aspect: 'before',
            mode: 'abstract',
            is_abstract: true,
            is_ref: false,
            is_aspect: true,
            operations: [],
            funcName: 'Watcher',
            refStatePath: undefined,
            refTargetQualifiedName: undefined,
            range: zeroRange,
        };
        const transitions = [
            {
                fromState: 'A',
                toState: 'B',
                event: repeatedEvent,
                guard: undefined,
                effects: [{text: ''}],
                parentPath: ['Root'],
                sourceKind: 'state',
                targetKind: 'state',
                forced: true,
                sourceStatePath: ['Root', 'A'],
                targetStatePath: ['Root', 'B'],
                triggerScope: 'chain',
                range: zeroRange,
            },
            {
                fromState: 'B',
                toState: 'C',
                event: repeatedEvent,
                guard: undefined,
                effects: [],
                parentPath: ['Root'],
                sourceKind: 'state',
                targetKind: 'state',
                forced: false,
                sourceStatePath: ['Root', 'B'],
                targetStatePath: ['Root', 'C'],
                triggerScope: 'chain',
                range: zeroRange,
            },
            {
                fromState: 'C',
                toState: 'EXIT_STATE',
                event: singleEvent,
                guard: undefined,
                effects: [],
                parentPath: ['Root'],
                sourceKind: 'state',
                targetKind: 'exit',
                forced: false,
                sourceStatePath: ['Root', 'C'],
                targetStatePath: undefined,
                triggerScope: 'absolute',
                range: zeroRange,
            },
        ];
        const machine = {
            filePath: '/tmp/stub.fcstm',
            defines: {},
            allStates: [{}, {}, {}],
            allEvents: [repeatedEvent, singleEvent],
            allTransitions: transitions,
            allActions: [enterRefAction, emptyDuringAction, aspectAction],
            lookups: {eventsByPathName: {}},
            rootState: {
                name: 'Root',
                pathName: 'Root',
                extraName: undefined,
                isPseudo: false,
                isLeafState: false,
                isRootState: true,
                range: zeroRange,
                events: {},
                onEnters: [enterRefAction],
                onDurings: [emptyDuringAction],
                onExits: [],
                onDuringAspects: [aspectAction],
                transitions,
                substates: {},
            },
        };

        const diagram = packageModule.buildFcstmDiagramFromStateMachine(machine as never);

        assert.ok(diagram);
        assert.equal(diagram!.eventLegend.length, 1);
        assert.equal(diagram!.eventLegend[0].label, 'Missing');
        assert.equal(diagram!.rootState.actions[0].qualifiedName, 'Root.<unnamed>');
        assert.equal(diagram!.rootState.actions[0].label, 'enter ref Root.Shared');
        assert.equal(diagram!.rootState.actions[1].label, 'during {}');
        assert.equal(diagram!.rootState.actions[2].label, '>> during before abstract Watcher');
        assert.equal(diagram!.rootState.transitions[0].label, '! A -> B /Missing effect');
        assert.deepEqual(diagram!.rootState.transitions[0].effectLines, [
            'effect {',
            '    ...',
            '}',
        ]);
        assert.equal(diagram!.rootState.transitions[2].triggerLabel, '/Solo');
        assert.equal(
            packageModule.formatFcstmDiagramTransitionLabel('A', 'B', '/Solo', 'x>0', false, true),
            '! A -> B /Solo if [x>0]'
        );
    });

    it('renders synthetic Mermaid diagrams that cover self-loops and skipped links', async () => {
        const leafState = (name: string) => ({
            id: `Root.${name}`,
            name,
            qualifiedName: `Root.${name}`,
            pseudo: false,
            leaf: true,
            root: false,
            range: zeroRange,
            events: [],
            actions: [],
            transitions: [],
            children: [],
        });
        const diagram = {
            kind: 'diagram',
            filePath: '',
            machineName: 'Synthetic',
            summary: {
                variables: 0,
                states: 6,
                events: 0,
                transitions: 5,
                actions: 0,
            },
            variables: [],
            eventLegend: [],
            rootState: {
                id: 'Root',
                name: 'Root',
                qualifiedName: 'Root',
                pseudo: false,
                leaf: false,
                root: true,
                range: zeroRange,
                events: [],
                actions: [],
                children: ['A', 'B', 'C', 'D', 'E'].map(leafState),
                transitions: [
                    {
                        id: 'init',
                        sourceLabel: '[*]',
                        targetLabel: 'A',
                        label: '[*] -> A',
                        effectLines: [],
                        forced: false,
                        sourceKind: 'init',
                        targetKind: 'state',
                        range: zeroRange,
                    },
                    {
                        id: 'self',
                        sourceLabel: 'A',
                        targetLabel: 'A',
                        label: 'A -> A',
                        triggerLabel: 'Ping',
                        guardLabel: 'x>0',
                        effectLines: [],
                        eventName: 'Ping',
                        eventRelativePath: 'Ping',
                        eventAbsolutePath: '/Ping',
                        triggerScope: 'local',
                        eventQualifiedName: 'Root.A.Ping',
                        forced: true,
                        sourceKind: 'state',
                        targetKind: 'state',
                        sourceStatePath: ['Root', 'A'],
                        targetStatePath: ['Root', 'A'],
                        range: zeroRange,
                    },
                    {
                        id: 'vertical',
                        sourceLabel: 'B',
                        targetLabel: 'E',
                        label: 'B -> E',
                        effectLines: [],
                        forced: false,
                        sourceKind: 'state',
                        targetKind: 'state',
                        range: zeroRange,
                    },
                    {
                        id: 'exit',
                        sourceLabel: 'C',
                        targetLabel: '[*]',
                        label: 'C -> [*]',
                        effectLines: [],
                        forced: false,
                        sourceKind: 'state',
                        targetKind: 'exit',
                        range: zeroRange,
                    },
                    {
                        id: 'skip',
                        sourceLabel: 'Ghost',
                        targetLabel: 'Missing',
                        label: 'Ghost -> Missing',
                        effectLines: [],
                        forced: false,
                        sourceKind: 'state',
                        targetKind: 'state',
                        range: zeroRange,
                    },
                ],
            },
        };

        const mermaid = await packageModule.renderFcstmDiagramMermaid(diagram as never, {
            direction: 'LR',
        });

        assert.match(mermaid, /^direction LR$/m);
        assert.doesNotMatch(mermaid, /state "Root \[5s\]" as state_\d+ \{/);
        assert.match(mermaid, /Ping \[x>0\]/);
        assert.match(mermaid, /\[\*\] --> state_\d+/);
        assert.match(mermaid, /state_\d+ --> \[\*\]/);
        assert.match(mermaid, /state "E" as state_\d+/);
        assert.doesNotMatch(mermaid, /Ghost -> Missing/);
    });

    it('still renders a root state when the machine has no child states', async () => {
        const diagram = {
            kind: 'diagram',
            filePath: '',
            machineName: 'SingleRoot',
            summary: {
                variables: 0,
                states: 1,
                events: 1,
                transitions: 0,
                actions: 1,
            },
            variables: [],
            eventLegend: [],
            rootState: {
                id: 'Root',
                name: 'Root',
                qualifiedName: 'Root',
                pseudo: false,
                leaf: true,
                root: true,
                range: zeroRange,
                events: [{
                    id: 'Root.Ping',
                    name: 'Ping',
                    qualifiedName: 'Root.Ping',
                    range: zeroRange,
                }],
                actions: [{
                    id: 'Root.enter',
                    name: 'Boot',
                    label: 'enter Boot',
                    qualifiedName: 'Root.enter',
                    stage: 'enter',
                    mode: 'operations',
                    operationCount: 1,
                    globalAspect: false,
                    range: zeroRange,
                }],
                transitions: [],
                children: [],
            },
        };

        const mermaid = await packageModule.renderFcstmDiagramMermaid(diagram as never, {
            detailLevel: 'full',
        });

        assert.match(mermaid, /state "Root" as state_\d+/);
        assert.match(mermaid, /state_\d+ : events: Ping/);
        assert.match(mermaid, /state_\d+ : actions: enter Boot/);
    });

    it('builds diagram IR from documents while honoring imported-file overlays', async () => {
        const dir = trackTempDir('jsfcstm-diagram-overlay-');
        const hostFile = path.join(dir, 'main.fcstm');
        const workerFile = path.join(dir, 'modules', 'motor.fcstm');
        const hostText = [
            'state Fleet {',
            '    import "./modules/motor.fcstm" as LeftMotor;',
            '    [*] -> LeftMotor;',
            '}',
        ].join('\n');

        writeFile(hostFile, hostText);
        writeFile(workerFile, [
            'state MotorRoot {',
            '    state Idle;',
            '}',
        ].join('\n'));

        const graph = packageModule.getWorkspaceGraph();
        graph.setOverlay(workerFile, [
            'state MotorRoot {',
            '    state Idle;',
            '    state Running;',
            '    [*] -> Idle;',
            '    Idle -> Running;',
            '}',
        ].join('\n'));

        const diagram = await packageModule.buildFcstmDiagramFromDocument(
            createDocument(hostText, hostFile)
        );

        assert.ok(diagram);
        assert.equal(diagram!.rootState.children.length, 1);
        assert.equal(diagram!.rootState.children[0].name, 'LeftMotor');
        assert.deepEqual(
            diagram!.rootState.children[0].children.map(child => child.name),
            ['Idle', 'Running']
        );
        assert.equal(diagram!.rootState.children[0].transitions[1].label, 'Idle -> Running');
    });
});
