// Generated by scripts/generate_model_sample_tests.py. Do not edit manually.
import {runPyGeneratedModelCase} from "./support";

runPyGeneratedModelCase({
    name: "dlc2.fcstm",
    relativeSourcePath: "dlc2.fcstm",
    source: "def int a = 0;\ndef int b = 0;\ndef int round_count = 0;\nstate TrafficLight {\n    state InService {\n        state Red;\n        state Yellow;\n        state Green;\n        event ServiceError;\n        event Start;\n        event Maintain;\n        Red -> [*] : ServiceError;\n        Red -> [*] : /GodDamnFuckUp;\n        Yellow -> [*] : ServiceError;\n        Yellow -> [*] : /GodDamnFuckUp;\n        Green -> [*] : ServiceError;\n        Green -> [*] : /GodDamnFuckUp;\n        [*] -> Red :: Start effect {\n            b = 1;\n        }\n        Red -> Green effect {\n            b = 3;\n        }\n        Green -> Yellow effect {\n            b = 2;\n        }\n        Yellow -> Red : if [a >= 10] effect {\n            b = 1;\n            round_count = round_count + 1;\n        }\n        Green -> Yellow : /Idle.E2;\n        Yellow -> Yellow : /E2;\n    }\n    state Idle {\n        state ToBe {\n            event E1;\n        }\n        state NotToBe {\n            event E1;\n            event E2;\n        }\n        event GiveUpThinking;\n        event E2;\n        ToBe -> [*] : GiveUpThinking;\n        ToBe -> [*] : /GodDamnFuckUp;\n        NotToBe -> [*] : GiveUpThinking;\n        NotToBe -> [*] : /GodDamnFuckUp;\n        [*] -> ToBe;\n        ToBe -> NotToBe :: E1;\n        NotToBe -> ToBe :: E1;\n        NotToBe -> [*] :: E2;\n    }\n    event GodDamnFuckUp;\n    event E2;\n    InService -> [*] :: ServiceError;\n    InService -> [*] : GodDamnFuckUp;\n    Idle -> InService :: GiveUpThinking;\n    Idle -> [*] : GodDamnFuckUp;\n    [*] -> InService;\n    InService -> Idle :: Maintain;\n    Idle -> Idle :: E2;\n    Idle -> [*];\n}",
    expected: {
    "defines": {
        "a": {
            "type": "int",
            "init": {
                "type": "Integer",
                "value": 0
            }
        },
        "b": {
            "type": "int",
            "init": {
                "type": "Integer",
                "value": 0
            }
        },
        "round_count": {
            "type": "int",
            "init": {
                "type": "Integer",
                "value": 0
            }
        }
    },
    "root_state": "TrafficLight",
    "walk_states": [
        "TrafficLight",
        "TrafficLight.InService",
        "TrafficLight.InService.Red",
        "TrafficLight.InService.Yellow",
        "TrafficLight.InService.Green",
        "TrafficLight.Idle",
        "TrafficLight.Idle.ToBe",
        "TrafficLight.Idle.NotToBe"
    ],
    "all_events": [
        {
            "name": "GodDamnFuckUp",
            "state_path": [
                "TrafficLight"
            ],
            "path": [
                "TrafficLight",
                "GodDamnFuckUp"
            ],
            "path_name": "TrafficLight.GodDamnFuckUp",
            "extra_name": null
        },
        {
            "name": "E2",
            "state_path": [
                "TrafficLight"
            ],
            "path": [
                "TrafficLight",
                "E2"
            ],
            "path_name": "TrafficLight.E2",
            "extra_name": null
        },
        {
            "name": "ServiceError",
            "state_path": [
                "TrafficLight",
                "InService"
            ],
            "path": [
                "TrafficLight",
                "InService",
                "ServiceError"
            ],
            "path_name": "TrafficLight.InService.ServiceError",
            "extra_name": null
        },
        {
            "name": "Start",
            "state_path": [
                "TrafficLight",
                "InService"
            ],
            "path": [
                "TrafficLight",
                "InService",
                "Start"
            ],
            "path_name": "TrafficLight.InService.Start",
            "extra_name": null
        },
        {
            "name": "Maintain",
            "state_path": [
                "TrafficLight",
                "InService"
            ],
            "path": [
                "TrafficLight",
                "InService",
                "Maintain"
            ],
            "path_name": "TrafficLight.InService.Maintain",
            "extra_name": null
        },
        {
            "name": "GiveUpThinking",
            "state_path": [
                "TrafficLight",
                "Idle"
            ],
            "path": [
                "TrafficLight",
                "Idle",
                "GiveUpThinking"
            ],
            "path_name": "TrafficLight.Idle.GiveUpThinking",
            "extra_name": null
        },
        {
            "name": "E2",
            "state_path": [
                "TrafficLight",
                "Idle"
            ],
            "path": [
                "TrafficLight",
                "Idle",
                "E2"
            ],
            "path_name": "TrafficLight.Idle.E2",
            "extra_name": null
        },
        {
            "name": "E1",
            "state_path": [
                "TrafficLight",
                "Idle",
                "ToBe"
            ],
            "path": [
                "TrafficLight",
                "Idle",
                "ToBe",
                "E1"
            ],
            "path_name": "TrafficLight.Idle.ToBe.E1",
            "extra_name": null
        },
        {
            "name": "E1",
            "state_path": [
                "TrafficLight",
                "Idle",
                "NotToBe"
            ],
            "path": [
                "TrafficLight",
                "Idle",
                "NotToBe",
                "E1"
            ],
            "path_name": "TrafficLight.Idle.NotToBe.E1",
            "extra_name": null
        },
        {
            "name": "E2",
            "state_path": [
                "TrafficLight",
                "Idle",
                "NotToBe"
            ],
            "path": [
                "TrafficLight",
                "Idle",
                "NotToBe",
                "E2"
            ],
            "path_name": "TrafficLight.Idle.NotToBe.E2",
            "extra_name": null
        }
    ],
    "all_actions": [],
    "states": {
        "TrafficLight": {
            "name": "TrafficLight",
            "path": [
                "TrafficLight"
            ],
            "parent": null,
            "substates": [
                "InService",
                "Idle"
            ],
            "events": {
                "E2": {
                    "name": "E2",
                    "state_path": [
                        "TrafficLight"
                    ],
                    "path": [
                        "TrafficLight",
                        "E2"
                    ],
                    "path_name": "TrafficLight.E2",
                    "extra_name": null
                },
                "GodDamnFuckUp": {
                    "name": "GodDamnFuckUp",
                    "state_path": [
                        "TrafficLight"
                    ],
                    "path": [
                        "TrafficLight",
                        "GodDamnFuckUp"
                    ],
                    "path_name": "TrafficLight.GodDamnFuckUp",
                    "extra_name": null
                }
            },
            "transitions": [
                {
                    "from_state": "InService",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.InService.ServiceError",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight"
                },
                {
                    "from_state": "InService",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.GodDamnFuckUp",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight"
                },
                {
                    "from_state": "Idle",
                    "to_state": "InService",
                    "event": "TrafficLight.Idle.GiveUpThinking",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight"
                },
                {
                    "from_state": "Idle",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.GodDamnFuckUp",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight"
                },
                {
                    "from_state": "INIT_STATE",
                    "to_state": "InService",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight"
                },
                {
                    "from_state": "InService",
                    "to_state": "Idle",
                    "event": "TrafficLight.InService.Maintain",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight"
                },
                {
                    "from_state": "Idle",
                    "to_state": "Idle",
                    "event": "TrafficLight.Idle.E2",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight"
                },
                {
                    "from_state": "Idle",
                    "to_state": "EXIT_STATE",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight"
                }
            ],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {
                "InService": 0,
                "Idle": 1
            },
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": true,
            "is_stoppable": false,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "InService",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight"
                }
            ],
            "transitions_from": [
                {
                    "from_state": "TrafficLight",
                    "to_state": "EXIT_STATE",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": null
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "TrafficLight",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": null
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "InService",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "InService",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight"
                }
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "TrafficLight",
                "TrafficLight.InService",
                "TrafficLight.InService.Red",
                "TrafficLight.InService.Yellow",
                "TrafficLight.InService.Green",
                "TrafficLight.Idle",
                "TrafficLight.Idle.ToBe",
                "TrafficLight.Idle.NotToBe"
            ]
        },
        "TrafficLight.InService": {
            "name": "InService",
            "path": [
                "TrafficLight",
                "InService"
            ],
            "parent": "TrafficLight",
            "substates": [
                "Red",
                "Yellow",
                "Green"
            ],
            "events": {
                "Maintain": {
                    "name": "Maintain",
                    "state_path": [
                        "TrafficLight",
                        "InService"
                    ],
                    "path": [
                        "TrafficLight",
                        "InService",
                        "Maintain"
                    ],
                    "path_name": "TrafficLight.InService.Maintain",
                    "extra_name": null
                },
                "ServiceError": {
                    "name": "ServiceError",
                    "state_path": [
                        "TrafficLight",
                        "InService"
                    ],
                    "path": [
                        "TrafficLight",
                        "InService",
                        "ServiceError"
                    ],
                    "path_name": "TrafficLight.InService.ServiceError",
                    "extra_name": null
                },
                "Start": {
                    "name": "Start",
                    "state_path": [
                        "TrafficLight",
                        "InService"
                    ],
                    "path": [
                        "TrafficLight",
                        "InService",
                        "Start"
                    ],
                    "path_name": "TrafficLight.InService.Start",
                    "extra_name": null
                }
            },
            "transitions": [
                {
                    "from_state": "Red",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.InService.ServiceError",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.InService"
                },
                {
                    "from_state": "Red",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.GodDamnFuckUp",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.InService"
                },
                {
                    "from_state": "Yellow",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.InService.ServiceError",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.InService"
                },
                {
                    "from_state": "Yellow",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.GodDamnFuckUp",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.InService"
                },
                {
                    "from_state": "Green",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.InService.ServiceError",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.InService"
                },
                {
                    "from_state": "Green",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.GodDamnFuckUp",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.InService"
                },
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Red",
                    "event": "TrafficLight.InService.Start",
                    "guard": null,
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "b",
                            "expr": {
                                "type": "Integer",
                                "value": 1
                            }
                        }
                    ],
                    "parent": "TrafficLight.InService"
                },
                {
                    "from_state": "Red",
                    "to_state": "Green",
                    "event": null,
                    "guard": null,
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "b",
                            "expr": {
                                "type": "Integer",
                                "value": 3
                            }
                        }
                    ],
                    "parent": "TrafficLight.InService"
                },
                {
                    "from_state": "Green",
                    "to_state": "Yellow",
                    "event": null,
                    "guard": null,
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "b",
                            "expr": {
                                "type": "Integer",
                                "value": 2
                            }
                        }
                    ],
                    "parent": "TrafficLight.InService"
                },
                {
                    "from_state": "Yellow",
                    "to_state": "Red",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": ">=",
                        "x": {
                            "type": "Variable",
                            "name": "a"
                        },
                        "y": {
                            "type": "Integer",
                            "value": 10
                        }
                    },
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "b",
                            "expr": {
                                "type": "Integer",
                                "value": 1
                            }
                        },
                        {
                            "type": "Operation",
                            "var_name": "round_count",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "round_count"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        }
                    ],
                    "parent": "TrafficLight.InService"
                },
                {
                    "from_state": "Green",
                    "to_state": "Yellow",
                    "event": "TrafficLight.Idle.E2",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.InService"
                },
                {
                    "from_state": "Yellow",
                    "to_state": "Yellow",
                    "event": "TrafficLight.E2",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.InService"
                }
            ],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {
                "Red": 0,
                "Yellow": 1,
                "Green": 2
            },
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": false,
            "is_stoppable": false,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Red",
                    "event": "TrafficLight.InService.Start",
                    "guard": null,
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "b",
                            "expr": {
                                "type": "Integer",
                                "value": 1
                            }
                        }
                    ],
                    "parent": "TrafficLight.InService"
                }
            ],
            "transitions_from": [
                {
                    "from_state": "InService",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.InService.ServiceError",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight"
                },
                {
                    "from_state": "InService",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.GodDamnFuckUp",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight"
                },
                {
                    "from_state": "InService",
                    "to_state": "Idle",
                    "event": "TrafficLight.InService.Maintain",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "Idle",
                    "to_state": "InService",
                    "event": "TrafficLight.Idle.GiveUpThinking",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight"
                },
                {
                    "from_state": "INIT_STATE",
                    "to_state": "InService",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight"
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Red",
                    "event": "TrafficLight.InService.Start",
                    "guard": null,
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "b",
                            "expr": {
                                "type": "Integer",
                                "value": 1
                            }
                        }
                    ],
                    "parent": "TrafficLight.InService"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Red",
                    "event": "TrafficLight.InService.Start",
                    "guard": null,
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "b",
                            "expr": {
                                "type": "Integer",
                                "value": 1
                            }
                        }
                    ],
                    "parent": "TrafficLight.InService"
                },
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "TrafficLight.InService",
                "TrafficLight.InService.Red",
                "TrafficLight.InService.Yellow",
                "TrafficLight.InService.Green"
            ]
        },
        "TrafficLight.InService.Red": {
            "name": "Red",
            "path": [
                "TrafficLight",
                "InService",
                "Red"
            ],
            "parent": "TrafficLight.InService",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "Red",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.InService.ServiceError",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.InService"
                },
                {
                    "from_state": "Red",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.GodDamnFuckUp",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.InService"
                },
                {
                    "from_state": "Red",
                    "to_state": "Green",
                    "event": null,
                    "guard": null,
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "b",
                            "expr": {
                                "type": "Integer",
                                "value": 3
                            }
                        }
                    ],
                    "parent": "TrafficLight.InService"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Red",
                    "event": "TrafficLight.InService.Start",
                    "guard": null,
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "b",
                            "expr": {
                                "type": "Integer",
                                "value": 1
                            }
                        }
                    ],
                    "parent": "TrafficLight.InService"
                },
                {
                    "from_state": "Yellow",
                    "to_state": "Red",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": ">=",
                        "x": {
                            "type": "Variable",
                            "name": "a"
                        },
                        "y": {
                            "type": "Integer",
                            "value": 10
                        }
                    },
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "b",
                            "expr": {
                                "type": "Integer",
                                "value": 1
                            }
                        },
                        {
                            "type": "Operation",
                            "var_name": "round_count",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "round_count"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        }
                    ],
                    "parent": "TrafficLight.InService"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "TrafficLight.InService.Red"
            ]
        },
        "TrafficLight.InService.Yellow": {
            "name": "Yellow",
            "path": [
                "TrafficLight",
                "InService",
                "Yellow"
            ],
            "parent": "TrafficLight.InService",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "Yellow",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.InService.ServiceError",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.InService"
                },
                {
                    "from_state": "Yellow",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.GodDamnFuckUp",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.InService"
                },
                {
                    "from_state": "Yellow",
                    "to_state": "Red",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": ">=",
                        "x": {
                            "type": "Variable",
                            "name": "a"
                        },
                        "y": {
                            "type": "Integer",
                            "value": 10
                        }
                    },
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "b",
                            "expr": {
                                "type": "Integer",
                                "value": 1
                            }
                        },
                        {
                            "type": "Operation",
                            "var_name": "round_count",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "round_count"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        }
                    ],
                    "parent": "TrafficLight.InService"
                },
                {
                    "from_state": "Yellow",
                    "to_state": "Yellow",
                    "event": "TrafficLight.E2",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.InService"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "Green",
                    "to_state": "Yellow",
                    "event": null,
                    "guard": null,
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "b",
                            "expr": {
                                "type": "Integer",
                                "value": 2
                            }
                        }
                    ],
                    "parent": "TrafficLight.InService"
                },
                {
                    "from_state": "Green",
                    "to_state": "Yellow",
                    "event": "TrafficLight.Idle.E2",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.InService"
                },
                {
                    "from_state": "Yellow",
                    "to_state": "Yellow",
                    "event": "TrafficLight.E2",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.InService"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "TrafficLight.InService.Yellow"
            ]
        },
        "TrafficLight.InService.Green": {
            "name": "Green",
            "path": [
                "TrafficLight",
                "InService",
                "Green"
            ],
            "parent": "TrafficLight.InService",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "Green",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.InService.ServiceError",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.InService"
                },
                {
                    "from_state": "Green",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.GodDamnFuckUp",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.InService"
                },
                {
                    "from_state": "Green",
                    "to_state": "Yellow",
                    "event": null,
                    "guard": null,
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "b",
                            "expr": {
                                "type": "Integer",
                                "value": 2
                            }
                        }
                    ],
                    "parent": "TrafficLight.InService"
                },
                {
                    "from_state": "Green",
                    "to_state": "Yellow",
                    "event": "TrafficLight.Idle.E2",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.InService"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "Red",
                    "to_state": "Green",
                    "event": null,
                    "guard": null,
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "b",
                            "expr": {
                                "type": "Integer",
                                "value": 3
                            }
                        }
                    ],
                    "parent": "TrafficLight.InService"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "TrafficLight.InService.Green"
            ]
        },
        "TrafficLight.Idle": {
            "name": "Idle",
            "path": [
                "TrafficLight",
                "Idle"
            ],
            "parent": "TrafficLight",
            "substates": [
                "ToBe",
                "NotToBe"
            ],
            "events": {
                "E2": {
                    "name": "E2",
                    "state_path": [
                        "TrafficLight",
                        "Idle"
                    ],
                    "path": [
                        "TrafficLight",
                        "Idle",
                        "E2"
                    ],
                    "path_name": "TrafficLight.Idle.E2",
                    "extra_name": null
                },
                "GiveUpThinking": {
                    "name": "GiveUpThinking",
                    "state_path": [
                        "TrafficLight",
                        "Idle"
                    ],
                    "path": [
                        "TrafficLight",
                        "Idle",
                        "GiveUpThinking"
                    ],
                    "path_name": "TrafficLight.Idle.GiveUpThinking",
                    "extra_name": null
                }
            },
            "transitions": [
                {
                    "from_state": "ToBe",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.Idle.GiveUpThinking",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.Idle"
                },
                {
                    "from_state": "ToBe",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.GodDamnFuckUp",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.Idle"
                },
                {
                    "from_state": "NotToBe",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.Idle.GiveUpThinking",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.Idle"
                },
                {
                    "from_state": "NotToBe",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.GodDamnFuckUp",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.Idle"
                },
                {
                    "from_state": "INIT_STATE",
                    "to_state": "ToBe",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.Idle"
                },
                {
                    "from_state": "ToBe",
                    "to_state": "NotToBe",
                    "event": "TrafficLight.Idle.ToBe.E1",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.Idle"
                },
                {
                    "from_state": "NotToBe",
                    "to_state": "ToBe",
                    "event": "TrafficLight.Idle.NotToBe.E1",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.Idle"
                },
                {
                    "from_state": "NotToBe",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.Idle.NotToBe.E2",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.Idle"
                }
            ],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {
                "ToBe": 0,
                "NotToBe": 1
            },
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": false,
            "is_stoppable": false,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "ToBe",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.Idle"
                }
            ],
            "transitions_from": [
                {
                    "from_state": "Idle",
                    "to_state": "InService",
                    "event": "TrafficLight.Idle.GiveUpThinking",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight"
                },
                {
                    "from_state": "Idle",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.GodDamnFuckUp",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight"
                },
                {
                    "from_state": "Idle",
                    "to_state": "Idle",
                    "event": "TrafficLight.Idle.E2",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight"
                },
                {
                    "from_state": "Idle",
                    "to_state": "EXIT_STATE",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "InService",
                    "to_state": "Idle",
                    "event": "TrafficLight.InService.Maintain",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight"
                },
                {
                    "from_state": "Idle",
                    "to_state": "Idle",
                    "event": "TrafficLight.Idle.E2",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight"
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "ToBe",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.Idle"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "ToBe",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.Idle"
                }
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "TrafficLight.Idle",
                "TrafficLight.Idle.ToBe",
                "TrafficLight.Idle.NotToBe"
            ]
        },
        "TrafficLight.Idle.ToBe": {
            "name": "ToBe",
            "path": [
                "TrafficLight",
                "Idle",
                "ToBe"
            ],
            "parent": "TrafficLight.Idle",
            "substates": [],
            "events": {
                "E1": {
                    "name": "E1",
                    "state_path": [
                        "TrafficLight",
                        "Idle",
                        "ToBe"
                    ],
                    "path": [
                        "TrafficLight",
                        "Idle",
                        "ToBe",
                        "E1"
                    ],
                    "path_name": "TrafficLight.Idle.ToBe.E1",
                    "extra_name": null
                }
            },
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "ToBe",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.Idle.GiveUpThinking",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.Idle"
                },
                {
                    "from_state": "ToBe",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.GodDamnFuckUp",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.Idle"
                },
                {
                    "from_state": "ToBe",
                    "to_state": "NotToBe",
                    "event": "TrafficLight.Idle.ToBe.E1",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.Idle"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "ToBe",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.Idle"
                },
                {
                    "from_state": "NotToBe",
                    "to_state": "ToBe",
                    "event": "TrafficLight.Idle.NotToBe.E1",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.Idle"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "TrafficLight.Idle.ToBe"
            ]
        },
        "TrafficLight.Idle.NotToBe": {
            "name": "NotToBe",
            "path": [
                "TrafficLight",
                "Idle",
                "NotToBe"
            ],
            "parent": "TrafficLight.Idle",
            "substates": [],
            "events": {
                "E1": {
                    "name": "E1",
                    "state_path": [
                        "TrafficLight",
                        "Idle",
                        "NotToBe"
                    ],
                    "path": [
                        "TrafficLight",
                        "Idle",
                        "NotToBe",
                        "E1"
                    ],
                    "path_name": "TrafficLight.Idle.NotToBe.E1",
                    "extra_name": null
                },
                "E2": {
                    "name": "E2",
                    "state_path": [
                        "TrafficLight",
                        "Idle",
                        "NotToBe"
                    ],
                    "path": [
                        "TrafficLight",
                        "Idle",
                        "NotToBe",
                        "E2"
                    ],
                    "path_name": "TrafficLight.Idle.NotToBe.E2",
                    "extra_name": null
                }
            },
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "NotToBe",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.Idle.GiveUpThinking",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.Idle"
                },
                {
                    "from_state": "NotToBe",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.GodDamnFuckUp",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.Idle"
                },
                {
                    "from_state": "NotToBe",
                    "to_state": "ToBe",
                    "event": "TrafficLight.Idle.NotToBe.E1",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.Idle"
                },
                {
                    "from_state": "NotToBe",
                    "to_state": "EXIT_STATE",
                    "event": "TrafficLight.Idle.NotToBe.E2",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.Idle"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "ToBe",
                    "to_state": "NotToBe",
                    "event": "TrafficLight.Idle.ToBe.E1",
                    "guard": null,
                    "effects": [],
                    "parent": "TrafficLight.Idle"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "TrafficLight.Idle.NotToBe"
            ]
        }
    },
    "ast": {
        "__class__": "StateMachineDSLProgram",
        "definitions": [
            {
                "__class__": "DefAssignment",
                "name": "a",
                "type": "int",
                "expr": {
                    "__class__": "Integer",
                    "raw": "0"
                }
            },
            {
                "__class__": "DefAssignment",
                "name": "b",
                "type": "int",
                "expr": {
                    "__class__": "Integer",
                    "raw": "0"
                }
            },
            {
                "__class__": "DefAssignment",
                "name": "round_count",
                "type": "int",
                "expr": {
                    "__class__": "Integer",
                    "raw": "0"
                }
            }
        ],
        "root_state": {
            "__class__": "StateDefinition",
            "name": "TrafficLight",
            "extra_name": null,
            "events": [
                {
                    "__class__": "EventDefinition",
                    "name": "GodDamnFuckUp",
                    "extra_name": null
                },
                {
                    "__class__": "EventDefinition",
                    "name": "E2",
                    "extra_name": null
                }
            ],
            "substates": [
                {
                    "__class__": "StateDefinition",
                    "name": "InService",
                    "extra_name": null,
                    "events": [
                        {
                            "__class__": "EventDefinition",
                            "name": "ServiceError",
                            "extra_name": null
                        },
                        {
                            "__class__": "EventDefinition",
                            "name": "Start",
                            "extra_name": null
                        },
                        {
                            "__class__": "EventDefinition",
                            "name": "Maintain",
                            "extra_name": null
                        }
                    ],
                    "substates": [
                        {
                            "__class__": "StateDefinition",
                            "name": "Red",
                            "extra_name": null,
                            "events": [],
                            "substates": [],
                            "transitions": [],
                            "enters": [],
                            "durings": [],
                            "exits": [],
                            "during_aspects": [],
                            "is_pseudo": false
                        },
                        {
                            "__class__": "StateDefinition",
                            "name": "Yellow",
                            "extra_name": null,
                            "events": [],
                            "substates": [],
                            "transitions": [],
                            "enters": [],
                            "durings": [],
                            "exits": [],
                            "during_aspects": [],
                            "is_pseudo": false
                        },
                        {
                            "__class__": "StateDefinition",
                            "name": "Green",
                            "extra_name": null,
                            "events": [],
                            "substates": [],
                            "transitions": [],
                            "enters": [],
                            "durings": [],
                            "exits": [],
                            "during_aspects": [],
                            "is_pseudo": false
                        }
                    ],
                    "transitions": [
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Red",
                            "to_state": "EXIT_STATE",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "ServiceError"
                                ],
                                "is_absolute": false
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Red",
                            "to_state": "EXIT_STATE",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "GodDamnFuckUp"
                                ],
                                "is_absolute": true
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Yellow",
                            "to_state": "EXIT_STATE",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "ServiceError"
                                ],
                                "is_absolute": false
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Yellow",
                            "to_state": "EXIT_STATE",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "GodDamnFuckUp"
                                ],
                                "is_absolute": true
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Green",
                            "to_state": "EXIT_STATE",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "ServiceError"
                                ],
                                "is_absolute": false
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Green",
                            "to_state": "EXIT_STATE",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "GodDamnFuckUp"
                                ],
                                "is_absolute": true
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "INIT_STATE",
                            "to_state": "Red",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "Start"
                                ],
                                "is_absolute": false
                            },
                            "condition_expr": null,
                            "post_operations": [
                                {
                                    "__class__": "OperationAssignment",
                                    "name": "b",
                                    "expr": {
                                        "__class__": "Integer",
                                        "raw": "1"
                                    }
                                }
                            ]
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Red",
                            "to_state": "Green",
                            "event_id": null,
                            "condition_expr": null,
                            "post_operations": [
                                {
                                    "__class__": "OperationAssignment",
                                    "name": "b",
                                    "expr": {
                                        "__class__": "Integer",
                                        "raw": "3"
                                    }
                                }
                            ]
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Green",
                            "to_state": "Yellow",
                            "event_id": null,
                            "condition_expr": null,
                            "post_operations": [
                                {
                                    "__class__": "OperationAssignment",
                                    "name": "b",
                                    "expr": {
                                        "__class__": "Integer",
                                        "raw": "2"
                                    }
                                }
                            ]
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Yellow",
                            "to_state": "Red",
                            "event_id": null,
                            "condition_expr": {
                                "__class__": "BinaryOp",
                                "expr1": {
                                    "__class__": "Name",
                                    "name": "a"
                                },
                                "op": ">=",
                                "expr2": {
                                    "__class__": "Integer",
                                    "raw": "10"
                                }
                            },
                            "post_operations": [
                                {
                                    "__class__": "OperationAssignment",
                                    "name": "b",
                                    "expr": {
                                        "__class__": "Integer",
                                        "raw": "1"
                                    }
                                },
                                {
                                    "__class__": "OperationAssignment",
                                    "name": "round_count",
                                    "expr": {
                                        "__class__": "BinaryOp",
                                        "expr1": {
                                            "__class__": "Name",
                                            "name": "round_count"
                                        },
                                        "op": "+",
                                        "expr2": {
                                            "__class__": "Integer",
                                            "raw": "1"
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Green",
                            "to_state": "Yellow",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "Idle",
                                    "E2"
                                ],
                                "is_absolute": true
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Yellow",
                            "to_state": "Yellow",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "E2"
                                ],
                                "is_absolute": true
                            },
                            "condition_expr": null,
                            "post_operations": []
                        }
                    ],
                    "enters": [],
                    "durings": [],
                    "exits": [],
                    "during_aspects": [],
                    "is_pseudo": false
                },
                {
                    "__class__": "StateDefinition",
                    "name": "Idle",
                    "extra_name": null,
                    "events": [
                        {
                            "__class__": "EventDefinition",
                            "name": "GiveUpThinking",
                            "extra_name": null
                        },
                        {
                            "__class__": "EventDefinition",
                            "name": "E2",
                            "extra_name": null
                        }
                    ],
                    "substates": [
                        {
                            "__class__": "StateDefinition",
                            "name": "ToBe",
                            "extra_name": null,
                            "events": [
                                {
                                    "__class__": "EventDefinition",
                                    "name": "E1",
                                    "extra_name": null
                                }
                            ],
                            "substates": [],
                            "transitions": [],
                            "enters": [],
                            "durings": [],
                            "exits": [],
                            "during_aspects": [],
                            "is_pseudo": false
                        },
                        {
                            "__class__": "StateDefinition",
                            "name": "NotToBe",
                            "extra_name": null,
                            "events": [
                                {
                                    "__class__": "EventDefinition",
                                    "name": "E1",
                                    "extra_name": null
                                },
                                {
                                    "__class__": "EventDefinition",
                                    "name": "E2",
                                    "extra_name": null
                                }
                            ],
                            "substates": [],
                            "transitions": [],
                            "enters": [],
                            "durings": [],
                            "exits": [],
                            "during_aspects": [],
                            "is_pseudo": false
                        }
                    ],
                    "transitions": [
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "ToBe",
                            "to_state": "EXIT_STATE",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "GiveUpThinking"
                                ],
                                "is_absolute": false
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "ToBe",
                            "to_state": "EXIT_STATE",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "GodDamnFuckUp"
                                ],
                                "is_absolute": true
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "NotToBe",
                            "to_state": "EXIT_STATE",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "GiveUpThinking"
                                ],
                                "is_absolute": false
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "NotToBe",
                            "to_state": "EXIT_STATE",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "GodDamnFuckUp"
                                ],
                                "is_absolute": true
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "INIT_STATE",
                            "to_state": "ToBe",
                            "event_id": null,
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "ToBe",
                            "to_state": "NotToBe",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "ToBe",
                                    "E1"
                                ],
                                "is_absolute": false
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "NotToBe",
                            "to_state": "ToBe",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "NotToBe",
                                    "E1"
                                ],
                                "is_absolute": false
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "NotToBe",
                            "to_state": "EXIT_STATE",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "NotToBe",
                                    "E2"
                                ],
                                "is_absolute": false
                            },
                            "condition_expr": null,
                            "post_operations": []
                        }
                    ],
                    "enters": [],
                    "durings": [],
                    "exits": [],
                    "during_aspects": [],
                    "is_pseudo": false
                }
            ],
            "transitions": [
                {
                    "__class__": "TransitionDefinition",
                    "from_state": "InService",
                    "to_state": "EXIT_STATE",
                    "event_id": {
                        "__class__": "ChainID",
                        "path": [
                            "InService",
                            "ServiceError"
                        ],
                        "is_absolute": false
                    },
                    "condition_expr": null,
                    "post_operations": []
                },
                {
                    "__class__": "TransitionDefinition",
                    "from_state": "InService",
                    "to_state": "EXIT_STATE",
                    "event_id": {
                        "__class__": "ChainID",
                        "path": [
                            "GodDamnFuckUp"
                        ],
                        "is_absolute": false
                    },
                    "condition_expr": null,
                    "post_operations": []
                },
                {
                    "__class__": "TransitionDefinition",
                    "from_state": "Idle",
                    "to_state": "InService",
                    "event_id": {
                        "__class__": "ChainID",
                        "path": [
                            "Idle",
                            "GiveUpThinking"
                        ],
                        "is_absolute": false
                    },
                    "condition_expr": null,
                    "post_operations": []
                },
                {
                    "__class__": "TransitionDefinition",
                    "from_state": "Idle",
                    "to_state": "EXIT_STATE",
                    "event_id": {
                        "__class__": "ChainID",
                        "path": [
                            "GodDamnFuckUp"
                        ],
                        "is_absolute": false
                    },
                    "condition_expr": null,
                    "post_operations": []
                },
                {
                    "__class__": "TransitionDefinition",
                    "from_state": "INIT_STATE",
                    "to_state": "InService",
                    "event_id": null,
                    "condition_expr": null,
                    "post_operations": []
                },
                {
                    "__class__": "TransitionDefinition",
                    "from_state": "InService",
                    "to_state": "Idle",
                    "event_id": {
                        "__class__": "ChainID",
                        "path": [
                            "InService",
                            "Maintain"
                        ],
                        "is_absolute": false
                    },
                    "condition_expr": null,
                    "post_operations": []
                },
                {
                    "__class__": "TransitionDefinition",
                    "from_state": "Idle",
                    "to_state": "Idle",
                    "event_id": {
                        "__class__": "ChainID",
                        "path": [
                            "Idle",
                            "E2"
                        ],
                        "is_absolute": false
                    },
                    "condition_expr": null,
                    "post_operations": []
                },
                {
                    "__class__": "TransitionDefinition",
                    "from_state": "Idle",
                    "to_state": "EXIT_STATE",
                    "event_id": null,
                    "condition_expr": null,
                    "post_operations": []
                }
            ],
            "enters": [],
            "durings": [],
            "exits": [],
            "during_aspects": [],
            "is_pseudo": false
        }
    }
},
});
