// Generated by scripts/generate_model_sample_tests.py. Do not edit manually.
import {runPyGeneratedModelCase} from "./support";

runPyGeneratedModelCase({
    name: "if_nested_temporaries.fcstm",
    relativeSourcePath: "if_nested_temporaries.fcstm",
    source: "def int x = 0;\ndef int y = 0;\ndef int z = 0;\ndef int flag = 0;\nstate Root {\n    state Active {\n        during {\n            tmp = x + 1;\n            if [flag > 0] {\n                tmp = tmp + 10;\n                if [y > 5] {\n                    bonus = y + 2;\n                    z = tmp + bonus;\n                } else {\n                    z = tmp - y;\n                }\n            } else if [x > 3] {\n                tmp = tmp + 20;\n                z = tmp;\n            } else {\n                z = tmp;\n            }\n            x = z + tmp;\n        }\n    }\n    [*] -> Active;\n}",
    files: undefined,
    entryFile: undefined,
    expected: {
    "defines": {
        "flag": {
            "type": "int",
            "init": {
                "type": "Integer",
                "value": 0
            }
        },
        "x": {
            "type": "int",
            "init": {
                "type": "Integer",
                "value": 0
            }
        },
        "y": {
            "type": "int",
            "init": {
                "type": "Integer",
                "value": 0
            }
        },
        "z": {
            "type": "int",
            "init": {
                "type": "Integer",
                "value": 0
            }
        }
    },
    "root_state": "Root",
    "walk_states": [
        "Root",
        "Root.Active"
    ],
    "all_events": [],
    "all_actions": [
        "Root.Active.<unnamed>"
    ],
    "states": {
        "Root": {
            "name": "Root",
            "path": [
                "Root"
            ],
            "parent": null,
            "substates": [
                "Active"
            ],
            "events": {},
            "transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Active",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Root"
                }
            ],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {
                "Active": 0
            },
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": true,
            "is_stoppable": false,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Active",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Root"
                }
            ],
            "transitions_from": [
                {
                    "from_state": "Root",
                    "to_state": "EXIT_STATE",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": null
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Root",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": null
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Active",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Root"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Active",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Root"
                }
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Root",
                "Root.Active"
            ]
        },
        "Root.Active": {
            "name": "Active",
            "path": [
                "Root",
                "Active"
            ],
            "parent": "Root",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [
                {
                    "type": "OnStage",
                    "stage": "during",
                    "aspect": null,
                    "name": null,
                    "doc": null,
                    "operations": [
                        {
                            "type": "Operation",
                            "var_name": "tmp",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "x"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        },
                        {
                            "type": "IfBlock",
                            "branches": [
                                {
                                    "condition": {
                                        "type": "BinaryOp",
                                        "op": ">",
                                        "x": {
                                            "type": "Variable",
                                            "name": "flag"
                                        },
                                        "y": {
                                            "type": "Integer",
                                            "value": 0
                                        }
                                    },
                                    "statements": [
                                        {
                                            "type": "Operation",
                                            "var_name": "tmp",
                                            "expr": {
                                                "type": "BinaryOp",
                                                "op": "+",
                                                "x": {
                                                    "type": "Variable",
                                                    "name": "tmp"
                                                },
                                                "y": {
                                                    "type": "Integer",
                                                    "value": 10
                                                }
                                            }
                                        },
                                        {
                                            "type": "IfBlock",
                                            "branches": [
                                                {
                                                    "condition": {
                                                        "type": "BinaryOp",
                                                        "op": ">",
                                                        "x": {
                                                            "type": "Variable",
                                                            "name": "y"
                                                        },
                                                        "y": {
                                                            "type": "Integer",
                                                            "value": 5
                                                        }
                                                    },
                                                    "statements": [
                                                        {
                                                            "type": "Operation",
                                                            "var_name": "bonus",
                                                            "expr": {
                                                                "type": "BinaryOp",
                                                                "op": "+",
                                                                "x": {
                                                                    "type": "Variable",
                                                                    "name": "y"
                                                                },
                                                                "y": {
                                                                    "type": "Integer",
                                                                    "value": 2
                                                                }
                                                            }
                                                        },
                                                        {
                                                            "type": "Operation",
                                                            "var_name": "z",
                                                            "expr": {
                                                                "type": "BinaryOp",
                                                                "op": "+",
                                                                "x": {
                                                                    "type": "Variable",
                                                                    "name": "tmp"
                                                                },
                                                                "y": {
                                                                    "type": "Variable",
                                                                    "name": "bonus"
                                                                }
                                                            }
                                                        }
                                                    ]
                                                },
                                                {
                                                    "condition": null,
                                                    "statements": [
                                                        {
                                                            "type": "Operation",
                                                            "var_name": "z",
                                                            "expr": {
                                                                "type": "BinaryOp",
                                                                "op": "-",
                                                                "x": {
                                                                    "type": "Variable",
                                                                    "name": "tmp"
                                                                },
                                                                "y": {
                                                                    "type": "Variable",
                                                                    "name": "y"
                                                                }
                                                            }
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "condition": {
                                        "type": "BinaryOp",
                                        "op": ">",
                                        "x": {
                                            "type": "Variable",
                                            "name": "x"
                                        },
                                        "y": {
                                            "type": "Integer",
                                            "value": 3
                                        }
                                    },
                                    "statements": [
                                        {
                                            "type": "Operation",
                                            "var_name": "tmp",
                                            "expr": {
                                                "type": "BinaryOp",
                                                "op": "+",
                                                "x": {
                                                    "type": "Variable",
                                                    "name": "tmp"
                                                },
                                                "y": {
                                                    "type": "Integer",
                                                    "value": 20
                                                }
                                            }
                                        },
                                        {
                                            "type": "Operation",
                                            "var_name": "z",
                                            "expr": {
                                                "type": "Variable",
                                                "name": "tmp"
                                            }
                                        }
                                    ]
                                },
                                {
                                    "condition": null,
                                    "statements": [
                                        {
                                            "type": "Operation",
                                            "var_name": "z",
                                            "expr": {
                                                "type": "Variable",
                                                "name": "tmp"
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "type": "Operation",
                            "var_name": "x",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "z"
                                },
                                "y": {
                                    "type": "Variable",
                                    "name": "tmp"
                                }
                            }
                        }
                    ],
                    "is_abstract": false,
                    "is_ref": false,
                    "is_aspect": false,
                    "state_path": [
                        "Root",
                        "Active",
                        null
                    ],
                    "func_name": "Root.Active.<unnamed>",
                    "parent": "Root.Active",
                    "ref_state_path": null,
                    "ref_resolved": false,
                    "ref_target_qualified_name": null
                }
            ],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [
                "Root.Active.<unnamed>"
            ],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Active",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Root"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [
                "Root.Active.<unnamed>"
            ],
            "list_on_durings_with_ids": [
                [
                    1,
                    "Root.Active.<unnamed>"
                ]
            ],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [
                [
                    "Root.Active",
                    "Root.Active.<unnamed>"
                ]
            ],
            "list_on_during_aspect_recursively_with_ids": [
                [
                    1,
                    "Root.Active",
                    "Root.Active.<unnamed>"
                ]
            ],
            "walk_states": [
                "Root.Active"
            ]
        }
    },
    "ast": {
        "__class__": "StateMachineDSLProgram",
        "definitions": [
            {
                "__class__": "DefAssignment",
                "name": "x",
                "type": "int",
                "expr": {
                    "__class__": "Integer",
                    "raw": "0"
                }
            },
            {
                "__class__": "DefAssignment",
                "name": "y",
                "type": "int",
                "expr": {
                    "__class__": "Integer",
                    "raw": "0"
                }
            },
            {
                "__class__": "DefAssignment",
                "name": "z",
                "type": "int",
                "expr": {
                    "__class__": "Integer",
                    "raw": "0"
                }
            },
            {
                "__class__": "DefAssignment",
                "name": "flag",
                "type": "int",
                "expr": {
                    "__class__": "Integer",
                    "raw": "0"
                }
            }
        ],
        "root_state": {
            "__class__": "StateDefinition",
            "name": "Root",
            "extra_name": null,
            "events": [],
            "substates": [
                {
                    "__class__": "StateDefinition",
                    "name": "Active",
                    "extra_name": null,
                    "events": [],
                    "substates": [],
                    "transitions": [],
                    "enters": [],
                    "durings": [
                        {
                            "__class__": "DuringOperations",
                            "name": null,
                            "aspect": null,
                            "doc": null,
                            "operations": [
                                {
                                    "__class__": "OperationAssignment",
                                    "name": "tmp",
                                    "expr": {
                                        "__class__": "BinaryOp",
                                        "expr1": {
                                            "__class__": "Name",
                                            "name": "x"
                                        },
                                        "op": "+",
                                        "expr2": {
                                            "__class__": "Integer",
                                            "raw": "1"
                                        }
                                    }
                                },
                                {
                                    "__class__": "OperationIf",
                                    "branches": [
                                        {
                                            "__class__": "OperationIfBranch",
                                            "condition": {
                                                "__class__": "BinaryOp",
                                                "expr1": {
                                                    "__class__": "Name",
                                                    "name": "flag"
                                                },
                                                "op": ">",
                                                "expr2": {
                                                    "__class__": "Integer",
                                                    "raw": "0"
                                                }
                                            },
                                            "statements": [
                                                {
                                                    "__class__": "OperationAssignment",
                                                    "name": "tmp",
                                                    "expr": {
                                                        "__class__": "BinaryOp",
                                                        "expr1": {
                                                            "__class__": "Name",
                                                            "name": "tmp"
                                                        },
                                                        "op": "+",
                                                        "expr2": {
                                                            "__class__": "Integer",
                                                            "raw": "10"
                                                        }
                                                    }
                                                },
                                                {
                                                    "__class__": "OperationIf",
                                                    "branches": [
                                                        {
                                                            "__class__": "OperationIfBranch",
                                                            "condition": {
                                                                "__class__": "BinaryOp",
                                                                "expr1": {
                                                                    "__class__": "Name",
                                                                    "name": "y"
                                                                },
                                                                "op": ">",
                                                                "expr2": {
                                                                    "__class__": "Integer",
                                                                    "raw": "5"
                                                                }
                                                            },
                                                            "statements": [
                                                                {
                                                                    "__class__": "OperationAssignment",
                                                                    "name": "bonus",
                                                                    "expr": {
                                                                        "__class__": "BinaryOp",
                                                                        "expr1": {
                                                                            "__class__": "Name",
                                                                            "name": "y"
                                                                        },
                                                                        "op": "+",
                                                                        "expr2": {
                                                                            "__class__": "Integer",
                                                                            "raw": "2"
                                                                        }
                                                                    }
                                                                },
                                                                {
                                                                    "__class__": "OperationAssignment",
                                                                    "name": "z",
                                                                    "expr": {
                                                                        "__class__": "BinaryOp",
                                                                        "expr1": {
                                                                            "__class__": "Name",
                                                                            "name": "tmp"
                                                                        },
                                                                        "op": "+",
                                                                        "expr2": {
                                                                            "__class__": "Name",
                                                                            "name": "bonus"
                                                                        }
                                                                    }
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            "__class__": "OperationIfBranch",
                                                            "condition": null,
                                                            "statements": [
                                                                {
                                                                    "__class__": "OperationAssignment",
                                                                    "name": "z",
                                                                    "expr": {
                                                                        "__class__": "BinaryOp",
                                                                        "expr1": {
                                                                            "__class__": "Name",
                                                                            "name": "tmp"
                                                                        },
                                                                        "op": "-",
                                                                        "expr2": {
                                                                            "__class__": "Name",
                                                                            "name": "y"
                                                                        }
                                                                    }
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            "__class__": "OperationIfBranch",
                                            "condition": {
                                                "__class__": "BinaryOp",
                                                "expr1": {
                                                    "__class__": "Name",
                                                    "name": "x"
                                                },
                                                "op": ">",
                                                "expr2": {
                                                    "__class__": "Integer",
                                                    "raw": "3"
                                                }
                                            },
                                            "statements": [
                                                {
                                                    "__class__": "OperationAssignment",
                                                    "name": "tmp",
                                                    "expr": {
                                                        "__class__": "BinaryOp",
                                                        "expr1": {
                                                            "__class__": "Name",
                                                            "name": "tmp"
                                                        },
                                                        "op": "+",
                                                        "expr2": {
                                                            "__class__": "Integer",
                                                            "raw": "20"
                                                        }
                                                    }
                                                },
                                                {
                                                    "__class__": "OperationAssignment",
                                                    "name": "z",
                                                    "expr": {
                                                        "__class__": "Name",
                                                        "name": "tmp"
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            "__class__": "OperationIfBranch",
                                            "condition": null,
                                            "statements": [
                                                {
                                                    "__class__": "OperationAssignment",
                                                    "name": "z",
                                                    "expr": {
                                                        "__class__": "Name",
                                                        "name": "tmp"
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "__class__": "OperationAssignment",
                                    "name": "x",
                                    "expr": {
                                        "__class__": "BinaryOp",
                                        "expr1": {
                                            "__class__": "Name",
                                            "name": "z"
                                        },
                                        "op": "+",
                                        "expr2": {
                                            "__class__": "Name",
                                            "name": "tmp"
                                        }
                                    }
                                }
                            ],
                            "ref": null
                        }
                    ],
                    "exits": [],
                    "during_aspects": [],
                    "is_pseudo": false
                }
            ],
            "transitions": [
                {
                    "__class__": "TransitionDefinition",
                    "from_state": "INIT_STATE",
                    "to_state": "Active",
                    "event_id": null,
                    "condition_expr": null,
                    "post_operations": []
                }
            ],
            "enters": [],
            "durings": [],
            "exits": [],
            "during_aspects": [],
            "is_pseudo": false
        }
    }
},
});
