// Generated by scripts/generate_model_sample_tests.py. Do not edit manually.
import {runPyGeneratedModelCase} from "./support";

runPyGeneratedModelCase({
    name: "dlc3.fcstm",
    relativeSourcePath: "dlc3.fcstm",
    source: "def int Event = 0;\nstate LX {\n    enter {\n    }\n    enter abstract act1;\n    state LX2 {\n        state start {\n            state LX4 {\n                state LX5;\n                LX5 -> [*] : /E1;\n                [*] -> LX5;\n            }\n            LX4 -> [*] : /E1;\n            [*] -> LX4;\n        }\n        start -> [*] : /E1;\n        [*] -> start;\n    }\n    state ERROR;\n    event E1;\n    LX2 -> ERROR : E1;\n    ERROR -> ERROR : E1;\n    [*] -> LX2;\n    ERROR -> [*];\n}",
    files: undefined,
    entryFile: undefined,
    expected: {
    "defines": {
        "Event": {
            "type": "int",
            "init": {
                "type": "Integer",
                "value": 0
            }
        }
    },
    "root_state": "LX",
    "walk_states": [
        "LX",
        "LX.LX2",
        "LX.LX2.start",
        "LX.LX2.start.LX4",
        "LX.LX2.start.LX4.LX5",
        "LX.ERROR"
    ],
    "all_events": [
        {
            "name": "E1",
            "state_path": [
                "LX"
            ],
            "path": [
                "LX",
                "E1"
            ],
            "path_name": "LX.E1",
            "extra_name": null
        }
    ],
    "all_actions": [
        "LX.<unnamed>",
        "LX.act1"
    ],
    "states": {
        "LX": {
            "name": "LX",
            "path": [
                "LX"
            ],
            "parent": null,
            "substates": [
                "LX2",
                "ERROR"
            ],
            "events": {
                "E1": {
                    "name": "E1",
                    "state_path": [
                        "LX"
                    ],
                    "path": [
                        "LX",
                        "E1"
                    ],
                    "path_name": "LX.E1",
                    "extra_name": null
                }
            },
            "transitions": [
                {
                    "from_state": "LX2",
                    "to_state": "ERROR",
                    "event": "LX.E1",
                    "guard": null,
                    "effects": [],
                    "parent": "LX"
                },
                {
                    "from_state": "ERROR",
                    "to_state": "ERROR",
                    "event": "LX.E1",
                    "guard": null,
                    "effects": [],
                    "parent": "LX"
                },
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LX2",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "LX"
                },
                {
                    "from_state": "ERROR",
                    "to_state": "EXIT_STATE",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "LX"
                }
            ],
            "named_functions": {
                "act1": {
                    "type": "OnStage",
                    "stage": "enter",
                    "aspect": null,
                    "name": "act1",
                    "doc": null,
                    "operations": [],
                    "is_abstract": true,
                    "is_ref": false,
                    "is_aspect": false,
                    "state_path": [
                        "LX",
                        "act1"
                    ],
                    "func_name": "LX.act1",
                    "parent": "LX",
                    "ref_state_path": null,
                    "ref_resolved": false,
                    "ref_target_qualified_name": null
                }
            },
            "on_enters": [
                {
                    "type": "OnStage",
                    "stage": "enter",
                    "aspect": null,
                    "name": null,
                    "doc": null,
                    "operations": [],
                    "is_abstract": false,
                    "is_ref": false,
                    "is_aspect": false,
                    "state_path": [
                        "LX",
                        null
                    ],
                    "func_name": "LX.<unnamed>",
                    "parent": "LX",
                    "ref_state_path": null,
                    "ref_resolved": false,
                    "ref_target_qualified_name": null
                },
                {
                    "type": "OnStage",
                    "stage": "enter",
                    "aspect": null,
                    "name": "act1",
                    "doc": null,
                    "operations": [],
                    "is_abstract": true,
                    "is_ref": false,
                    "is_aspect": false,
                    "state_path": [
                        "LX",
                        "act1"
                    ],
                    "func_name": "LX.act1",
                    "parent": "LX",
                    "ref_state_path": null,
                    "ref_resolved": false,
                    "ref_target_qualified_name": null
                }
            ],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {
                "LX2": 0,
                "ERROR": 1
            },
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": true,
            "is_stoppable": false,
            "abstract_on_enters": [
                "LX.act1"
            ],
            "non_abstract_on_enters": [
                "LX.<unnamed>"
            ],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LX2",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "LX"
                }
            ],
            "transitions_from": [
                {
                    "from_state": "LX",
                    "to_state": "EXIT_STATE",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": null
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LX",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": null
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LX2",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "LX"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LX2",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "LX"
                }
            ],
            "list_on_enters": [
                "LX.<unnamed>",
                "LX.act1"
            ],
            "list_on_enters_with_ids": [
                [
                    1,
                    "LX.<unnamed>"
                ],
                [
                    2,
                    "LX.act1"
                ]
            ],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "LX",
                "LX.LX2",
                "LX.LX2.start",
                "LX.LX2.start.LX4",
                "LX.LX2.start.LX4.LX5",
                "LX.ERROR"
            ]
        },
        "LX.LX2": {
            "name": "LX2",
            "path": [
                "LX",
                "LX2"
            ],
            "parent": "LX",
            "substates": [
                "start"
            ],
            "events": {},
            "transitions": [
                {
                    "from_state": "start",
                    "to_state": "EXIT_STATE",
                    "event": "LX.E1",
                    "guard": null,
                    "effects": [],
                    "parent": "LX.LX2"
                },
                {
                    "from_state": "INIT_STATE",
                    "to_state": "start",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "LX.LX2"
                }
            ],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {
                "start": 0
            },
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": false,
            "is_stoppable": false,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "start",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "LX.LX2"
                }
            ],
            "transitions_from": [
                {
                    "from_state": "LX2",
                    "to_state": "ERROR",
                    "event": "LX.E1",
                    "guard": null,
                    "effects": [],
                    "parent": "LX"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LX2",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "LX"
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "start",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "LX.LX2"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "start",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "LX.LX2"
                }
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "LX.LX2",
                "LX.LX2.start",
                "LX.LX2.start.LX4",
                "LX.LX2.start.LX4.LX5"
            ]
        },
        "LX.LX2.start": {
            "name": "start",
            "path": [
                "LX",
                "LX2",
                "start"
            ],
            "parent": "LX.LX2",
            "substates": [
                "LX4"
            ],
            "events": {},
            "transitions": [
                {
                    "from_state": "LX4",
                    "to_state": "EXIT_STATE",
                    "event": "LX.E1",
                    "guard": null,
                    "effects": [],
                    "parent": "LX.LX2.start"
                },
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LX4",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "LX.LX2.start"
                }
            ],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {
                "LX4": 0
            },
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": false,
            "is_stoppable": false,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LX4",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "LX.LX2.start"
                }
            ],
            "transitions_from": [
                {
                    "from_state": "start",
                    "to_state": "EXIT_STATE",
                    "event": "LX.E1",
                    "guard": null,
                    "effects": [],
                    "parent": "LX.LX2"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "start",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "LX.LX2"
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LX4",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "LX.LX2.start"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LX4",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "LX.LX2.start"
                }
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "LX.LX2.start",
                "LX.LX2.start.LX4",
                "LX.LX2.start.LX4.LX5"
            ]
        },
        "LX.LX2.start.LX4": {
            "name": "LX4",
            "path": [
                "LX",
                "LX2",
                "start",
                "LX4"
            ],
            "parent": "LX.LX2.start",
            "substates": [
                "LX5"
            ],
            "events": {},
            "transitions": [
                {
                    "from_state": "LX5",
                    "to_state": "EXIT_STATE",
                    "event": "LX.E1",
                    "guard": null,
                    "effects": [],
                    "parent": "LX.LX2.start.LX4"
                },
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LX5",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "LX.LX2.start.LX4"
                }
            ],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {
                "LX5": 0
            },
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": false,
            "is_stoppable": false,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LX5",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "LX.LX2.start.LX4"
                }
            ],
            "transitions_from": [
                {
                    "from_state": "LX4",
                    "to_state": "EXIT_STATE",
                    "event": "LX.E1",
                    "guard": null,
                    "effects": [],
                    "parent": "LX.LX2.start"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LX4",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "LX.LX2.start"
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LX5",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "LX.LX2.start.LX4"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LX5",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "LX.LX2.start.LX4"
                }
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "LX.LX2.start.LX4",
                "LX.LX2.start.LX4.LX5"
            ]
        },
        "LX.LX2.start.LX4.LX5": {
            "name": "LX5",
            "path": [
                "LX",
                "LX2",
                "start",
                "LX4",
                "LX5"
            ],
            "parent": "LX.LX2.start.LX4",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "LX5",
                    "to_state": "EXIT_STATE",
                    "event": "LX.E1",
                    "guard": null,
                    "effects": [],
                    "parent": "LX.LX2.start.LX4"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LX5",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "LX.LX2.start.LX4"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "LX.LX2.start.LX4.LX5"
            ]
        },
        "LX.ERROR": {
            "name": "ERROR",
            "path": [
                "LX",
                "ERROR"
            ],
            "parent": "LX",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "ERROR",
                    "to_state": "ERROR",
                    "event": "LX.E1",
                    "guard": null,
                    "effects": [],
                    "parent": "LX"
                },
                {
                    "from_state": "ERROR",
                    "to_state": "EXIT_STATE",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "LX"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "LX2",
                    "to_state": "ERROR",
                    "event": "LX.E1",
                    "guard": null,
                    "effects": [],
                    "parent": "LX"
                },
                {
                    "from_state": "ERROR",
                    "to_state": "ERROR",
                    "event": "LX.E1",
                    "guard": null,
                    "effects": [],
                    "parent": "LX"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "LX.ERROR"
            ]
        }
    },
    "ast": {
        "__class__": "StateMachineDSLProgram",
        "definitions": [
            {
                "__class__": "DefAssignment",
                "name": "Event",
                "type": "int",
                "expr": {
                    "__class__": "Integer",
                    "raw": "0"
                }
            }
        ],
        "root_state": {
            "__class__": "StateDefinition",
            "name": "LX",
            "extra_name": null,
            "events": [
                {
                    "__class__": "EventDefinition",
                    "name": "E1",
                    "extra_name": null
                }
            ],
            "substates": [
                {
                    "__class__": "StateDefinition",
                    "name": "LX2",
                    "extra_name": null,
                    "events": [],
                    "substates": [
                        {
                            "__class__": "StateDefinition",
                            "name": "start",
                            "extra_name": null,
                            "events": [],
                            "substates": [
                                {
                                    "__class__": "StateDefinition",
                                    "name": "LX4",
                                    "extra_name": null,
                                    "events": [],
                                    "substates": [
                                        {
                                            "__class__": "StateDefinition",
                                            "name": "LX5",
                                            "extra_name": null,
                                            "events": [],
                                            "substates": [],
                                            "transitions": [],
                                            "enters": [],
                                            "durings": [],
                                            "exits": [],
                                            "during_aspects": [],
                                            "is_pseudo": false
                                        }
                                    ],
                                    "transitions": [
                                        {
                                            "__class__": "TransitionDefinition",
                                            "from_state": "LX5",
                                            "to_state": "EXIT_STATE",
                                            "event_id": {
                                                "__class__": "ChainID",
                                                "path": [
                                                    "E1"
                                                ],
                                                "is_absolute": true
                                            },
                                            "condition_expr": null,
                                            "post_operations": []
                                        },
                                        {
                                            "__class__": "TransitionDefinition",
                                            "from_state": "INIT_STATE",
                                            "to_state": "LX5",
                                            "event_id": null,
                                            "condition_expr": null,
                                            "post_operations": []
                                        }
                                    ],
                                    "enters": [],
                                    "durings": [],
                                    "exits": [],
                                    "during_aspects": [],
                                    "is_pseudo": false
                                }
                            ],
                            "transitions": [
                                {
                                    "__class__": "TransitionDefinition",
                                    "from_state": "LX4",
                                    "to_state": "EXIT_STATE",
                                    "event_id": {
                                        "__class__": "ChainID",
                                        "path": [
                                            "E1"
                                        ],
                                        "is_absolute": true
                                    },
                                    "condition_expr": null,
                                    "post_operations": []
                                },
                                {
                                    "__class__": "TransitionDefinition",
                                    "from_state": "INIT_STATE",
                                    "to_state": "LX4",
                                    "event_id": null,
                                    "condition_expr": null,
                                    "post_operations": []
                                }
                            ],
                            "enters": [],
                            "durings": [],
                            "exits": [],
                            "during_aspects": [],
                            "is_pseudo": false
                        }
                    ],
                    "transitions": [
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "start",
                            "to_state": "EXIT_STATE",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "E1"
                                ],
                                "is_absolute": true
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "INIT_STATE",
                            "to_state": "start",
                            "event_id": null,
                            "condition_expr": null,
                            "post_operations": []
                        }
                    ],
                    "enters": [],
                    "durings": [],
                    "exits": [],
                    "during_aspects": [],
                    "is_pseudo": false
                },
                {
                    "__class__": "StateDefinition",
                    "name": "ERROR",
                    "extra_name": null,
                    "events": [],
                    "substates": [],
                    "transitions": [],
                    "enters": [],
                    "durings": [],
                    "exits": [],
                    "during_aspects": [],
                    "is_pseudo": false
                }
            ],
            "transitions": [
                {
                    "__class__": "TransitionDefinition",
                    "from_state": "LX2",
                    "to_state": "ERROR",
                    "event_id": {
                        "__class__": "ChainID",
                        "path": [
                            "E1"
                        ],
                        "is_absolute": false
                    },
                    "condition_expr": null,
                    "post_operations": []
                },
                {
                    "__class__": "TransitionDefinition",
                    "from_state": "ERROR",
                    "to_state": "ERROR",
                    "event_id": {
                        "__class__": "ChainID",
                        "path": [
                            "E1"
                        ],
                        "is_absolute": false
                    },
                    "condition_expr": null,
                    "post_operations": []
                },
                {
                    "__class__": "TransitionDefinition",
                    "from_state": "INIT_STATE",
                    "to_state": "LX2",
                    "event_id": null,
                    "condition_expr": null,
                    "post_operations": []
                },
                {
                    "__class__": "TransitionDefinition",
                    "from_state": "ERROR",
                    "to_state": "EXIT_STATE",
                    "event_id": null,
                    "condition_expr": null,
                    "post_operations": []
                }
            ],
            "enters": [
                {
                    "__class__": "EnterOperations",
                    "name": null,
                    "aspect": null,
                    "doc": null,
                    "operations": [],
                    "ref": null
                },
                {
                    "__class__": "EnterAbstractFunction",
                    "name": "act1",
                    "aspect": null,
                    "doc": null,
                    "operations": null,
                    "ref": null
                }
            ],
            "durings": [],
            "exits": [],
            "during_aspects": [],
            "is_pseudo": false
        }
    }
},
});
