// Generated by scripts/generate_model_sample_tests.py. Do not edit manually.
import {runPyGeneratedModelCase} from "./support";

runPyGeneratedModelCase({
    name: "import_phase2_demo",
    relativeSourcePath: "import_phase2_demo",
    source: "state System {\n    state LeftMotor named 'Left Motor' {\n        enter abstract InitMotor;\n        state Idle {\n            event Start;\n        }\n        state Running {\n            state Spin;\n            [*] -> Spin;\n        }\n        event Reset;\n        [*] -> Idle;\n        Idle -> Running :: Start;\n        Running -> Idle : Reset;\n    }\n    [*] -> LeftMotor;\n}",
    files: [
    [
        "main.fcstm",
        "state System {\n    import \"./modules/motor.fcstm\" as LeftMotor named \"Left Motor\";\n    [*] -> LeftMotor;\n}\n"
    ],
    [
        "modules/motor.fcstm",
        "state MotorRoot named \"Motor Module\" {\n    enter abstract InitMotor;\n    state Idle;\n    state Running {\n        state Spin;\n        [*] -> Spin;\n    }\n    [*] -> Idle;\n    Idle -> Running :: Start;\n    Running -> Idle : /Reset;\n}\n"
    ]
],
    entryFile: "main.fcstm",
    expected: {
    "defines": {},
    "root_state": "System",
    "walk_states": [
        "System",
        "System.LeftMotor",
        "System.LeftMotor.Idle",
        "System.LeftMotor.Running",
        "System.LeftMotor.Running.Spin"
    ],
    "all_events": [
        {
            "name": "Reset",
            "state_path": [
                "System",
                "LeftMotor"
            ],
            "path": [
                "System",
                "LeftMotor",
                "Reset"
            ],
            "path_name": "System.LeftMotor.Reset",
            "extra_name": null
        },
        {
            "name": "Start",
            "state_path": [
                "System",
                "LeftMotor",
                "Idle"
            ],
            "path": [
                "System",
                "LeftMotor",
                "Idle",
                "Start"
            ],
            "path_name": "System.LeftMotor.Idle.Start",
            "extra_name": null
        }
    ],
    "all_actions": [
        "System.LeftMotor.InitMotor"
    ],
    "states": {
        "System": {
            "name": "System",
            "path": [
                "System"
            ],
            "parent": null,
            "substates": [
                "LeftMotor"
            ],
            "events": {},
            "transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LeftMotor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "System"
                }
            ],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {
                "LeftMotor": 0
            },
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": true,
            "is_stoppable": false,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LeftMotor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "System"
                }
            ],
            "transitions_from": [
                {
                    "from_state": "System",
                    "to_state": "EXIT_STATE",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": null
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "System",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": null
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LeftMotor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "System"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LeftMotor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "System"
                }
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "System",
                "System.LeftMotor",
                "System.LeftMotor.Idle",
                "System.LeftMotor.Running",
                "System.LeftMotor.Running.Spin"
            ]
        },
        "System.LeftMotor": {
            "name": "LeftMotor",
            "path": [
                "System",
                "LeftMotor"
            ],
            "parent": "System",
            "substates": [
                "Idle",
                "Running"
            ],
            "events": {
                "Reset": {
                    "name": "Reset",
                    "state_path": [
                        "System",
                        "LeftMotor"
                    ],
                    "path": [
                        "System",
                        "LeftMotor",
                        "Reset"
                    ],
                    "path_name": "System.LeftMotor.Reset",
                    "extra_name": null
                }
            },
            "transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "System.LeftMotor"
                },
                {
                    "from_state": "Idle",
                    "to_state": "Running",
                    "event": "System.LeftMotor.Idle.Start",
                    "guard": null,
                    "effects": [],
                    "parent": "System.LeftMotor"
                },
                {
                    "from_state": "Running",
                    "to_state": "Idle",
                    "event": "System.LeftMotor.Reset",
                    "guard": null,
                    "effects": [],
                    "parent": "System.LeftMotor"
                }
            ],
            "named_functions": {
                "InitMotor": {
                    "type": "OnStage",
                    "stage": "enter",
                    "aspect": null,
                    "name": "InitMotor",
                    "doc": null,
                    "operations": [],
                    "is_abstract": true,
                    "is_ref": false,
                    "is_aspect": false,
                    "state_path": [
                        "System",
                        "LeftMotor",
                        "InitMotor"
                    ],
                    "func_name": "System.LeftMotor.InitMotor",
                    "parent": "System.LeftMotor",
                    "ref_state_path": null,
                    "ref_resolved": false,
                    "ref_target_qualified_name": null
                }
            },
            "on_enters": [
                {
                    "type": "OnStage",
                    "stage": "enter",
                    "aspect": null,
                    "name": "InitMotor",
                    "doc": null,
                    "operations": [],
                    "is_abstract": true,
                    "is_ref": false,
                    "is_aspect": false,
                    "state_path": [
                        "System",
                        "LeftMotor",
                        "InitMotor"
                    ],
                    "func_name": "System.LeftMotor.InitMotor",
                    "parent": "System.LeftMotor",
                    "ref_state_path": null,
                    "ref_resolved": false,
                    "ref_target_qualified_name": null
                }
            ],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {
                "Idle": 0,
                "Running": 1
            },
            "extra_name": "Left Motor",
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": false,
            "is_stoppable": false,
            "abstract_on_enters": [
                "System.LeftMotor.InitMotor"
            ],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "System.LeftMotor"
                }
            ],
            "transitions_from": [],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LeftMotor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "System"
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "System.LeftMotor"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "System.LeftMotor"
                }
            ],
            "list_on_enters": [
                "System.LeftMotor.InitMotor"
            ],
            "list_on_enters_with_ids": [
                [
                    1,
                    "System.LeftMotor.InitMotor"
                ]
            ],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "System.LeftMotor",
                "System.LeftMotor.Idle",
                "System.LeftMotor.Running",
                "System.LeftMotor.Running.Spin"
            ]
        },
        "System.LeftMotor.Idle": {
            "name": "Idle",
            "path": [
                "System",
                "LeftMotor",
                "Idle"
            ],
            "parent": "System.LeftMotor",
            "substates": [],
            "events": {
                "Start": {
                    "name": "Start",
                    "state_path": [
                        "System",
                        "LeftMotor",
                        "Idle"
                    ],
                    "path": [
                        "System",
                        "LeftMotor",
                        "Idle",
                        "Start"
                    ],
                    "path_name": "System.LeftMotor.Idle.Start",
                    "extra_name": null
                }
            },
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "Idle",
                    "to_state": "Running",
                    "event": "System.LeftMotor.Idle.Start",
                    "guard": null,
                    "effects": [],
                    "parent": "System.LeftMotor"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "System.LeftMotor"
                },
                {
                    "from_state": "Running",
                    "to_state": "Idle",
                    "event": "System.LeftMotor.Reset",
                    "guard": null,
                    "effects": [],
                    "parent": "System.LeftMotor"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "System.LeftMotor.Idle"
            ]
        },
        "System.LeftMotor.Running": {
            "name": "Running",
            "path": [
                "System",
                "LeftMotor",
                "Running"
            ],
            "parent": "System.LeftMotor",
            "substates": [
                "Spin"
            ],
            "events": {},
            "transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Spin",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "System.LeftMotor.Running"
                }
            ],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {
                "Spin": 0
            },
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": false,
            "is_stoppable": false,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Spin",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "System.LeftMotor.Running"
                }
            ],
            "transitions_from": [
                {
                    "from_state": "Running",
                    "to_state": "Idle",
                    "event": "System.LeftMotor.Reset",
                    "guard": null,
                    "effects": [],
                    "parent": "System.LeftMotor"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "Idle",
                    "to_state": "Running",
                    "event": "System.LeftMotor.Idle.Start",
                    "guard": null,
                    "effects": [],
                    "parent": "System.LeftMotor"
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Spin",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "System.LeftMotor.Running"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Spin",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "System.LeftMotor.Running"
                }
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "System.LeftMotor.Running",
                "System.LeftMotor.Running.Spin"
            ]
        },
        "System.LeftMotor.Running.Spin": {
            "name": "Spin",
            "path": [
                "System",
                "LeftMotor",
                "Running",
                "Spin"
            ],
            "parent": "System.LeftMotor.Running",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Spin",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "System.LeftMotor.Running"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "System.LeftMotor.Running.Spin"
            ]
        }
    },
    "ast": {
        "__class__": "StateMachineDSLProgram",
        "definitions": [],
        "root_state": {
            "__class__": "StateDefinition",
            "name": "System",
            "extra_name": null,
            "events": [],
            "substates": [
                {
                    "__class__": "StateDefinition",
                    "name": "LeftMotor",
                    "extra_name": "Left Motor",
                    "events": [
                        {
                            "__class__": "EventDefinition",
                            "name": "Reset",
                            "extra_name": null
                        }
                    ],
                    "substates": [
                        {
                            "__class__": "StateDefinition",
                            "name": "Idle",
                            "extra_name": null,
                            "events": [
                                {
                                    "__class__": "EventDefinition",
                                    "name": "Start",
                                    "extra_name": null
                                }
                            ],
                            "substates": [],
                            "transitions": [],
                            "enters": [],
                            "durings": [],
                            "exits": [],
                            "during_aspects": [],
                            "is_pseudo": false
                        },
                        {
                            "__class__": "StateDefinition",
                            "name": "Running",
                            "extra_name": null,
                            "events": [],
                            "substates": [
                                {
                                    "__class__": "StateDefinition",
                                    "name": "Spin",
                                    "extra_name": null,
                                    "events": [],
                                    "substates": [],
                                    "transitions": [],
                                    "enters": [],
                                    "durings": [],
                                    "exits": [],
                                    "during_aspects": [],
                                    "is_pseudo": false
                                }
                            ],
                            "transitions": [
                                {
                                    "__class__": "TransitionDefinition",
                                    "from_state": "INIT_STATE",
                                    "to_state": "Spin",
                                    "event_id": null,
                                    "condition_expr": null,
                                    "post_operations": []
                                }
                            ],
                            "enters": [],
                            "durings": [],
                            "exits": [],
                            "during_aspects": [],
                            "is_pseudo": false
                        }
                    ],
                    "transitions": [
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "INIT_STATE",
                            "to_state": "Idle",
                            "event_id": null,
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Idle",
                            "to_state": "Running",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "Idle",
                                    "Start"
                                ],
                                "is_absolute": false
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Running",
                            "to_state": "Idle",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "Reset"
                                ],
                                "is_absolute": false
                            },
                            "condition_expr": null,
                            "post_operations": []
                        }
                    ],
                    "enters": [
                        {
                            "__class__": "EnterAbstractFunction",
                            "name": "InitMotor",
                            "aspect": null,
                            "doc": null,
                            "operations": null,
                            "ref": null
                        }
                    ],
                    "durings": [],
                    "exits": [],
                    "during_aspects": [],
                    "is_pseudo": false
                }
            ],
            "transitions": [
                {
                    "__class__": "TransitionDefinition",
                    "from_state": "INIT_STATE",
                    "to_state": "LeftMotor",
                    "event_id": null,
                    "condition_expr": null,
                    "post_operations": []
                }
            ],
            "enters": [],
            "durings": [],
            "exits": [],
            "during_aspects": [],
            "is_pseudo": false
        }
    }
},
});
