// Generated by scripts/generate_model_sample_tests.py. Do not edit manually.
import {runPyGeneratedModelCase} from "./support";

runPyGeneratedModelCase({
    name: "import_phase4_nested_targets",
    relativeSourcePath: "import_phase4_nested_targets",
    source: "state Plant {\n    state Worker named 'Mapped Worker' {\n        state Idle;\n        state Failed;\n        state Halted;\n        [*] -> Idle;\n        Idle -> Failed : /GlobalFault;\n        Failed -> Halted : /Bus.Stop;\n        Halted -> Idle : /Bus.Reset;\n    }\n    state Bus {\n        event Stop named 'Plant Stop';\n        event Reset named 'Local Reset';\n    }\n    event GlobalFault named 'Global Fault';\n    [*] -> Worker;\n}",
    expected: {
    "defines": {},
    "root_state": "Plant",
    "walk_states": [
        "Plant",
        "Plant.Worker",
        "Plant.Worker.Idle",
        "Plant.Worker.Failed",
        "Plant.Worker.Halted",
        "Plant.Bus"
    ],
    "all_events": [
        {
            "name": "GlobalFault",
            "state_path": [
                "Plant"
            ],
            "path": [
                "Plant",
                "GlobalFault"
            ],
            "path_name": "Plant.GlobalFault",
            "extra_name": "Global Fault"
        },
        {
            "name": "Stop",
            "state_path": [
                "Plant",
                "Bus"
            ],
            "path": [
                "Plant",
                "Bus",
                "Stop"
            ],
            "path_name": "Plant.Bus.Stop",
            "extra_name": "Plant Stop"
        },
        {
            "name": "Reset",
            "state_path": [
                "Plant",
                "Bus"
            ],
            "path": [
                "Plant",
                "Bus",
                "Reset"
            ],
            "path_name": "Plant.Bus.Reset",
            "extra_name": "Local Reset"
        }
    ],
    "all_actions": [],
    "states": {
        "Plant": {
            "name": "Plant",
            "path": [
                "Plant"
            ],
            "parent": null,
            "substates": [
                "Worker",
                "Bus"
            ],
            "events": {
                "GlobalFault": {
                    "name": "GlobalFault",
                    "state_path": [
                        "Plant"
                    ],
                    "path": [
                        "Plant",
                        "GlobalFault"
                    ],
                    "path_name": "Plant.GlobalFault",
                    "extra_name": "Global Fault"
                }
            },
            "transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Worker",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Plant"
                }
            ],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {
                "Worker": 0,
                "Bus": 1
            },
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": true,
            "is_stoppable": false,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Worker",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Plant"
                }
            ],
            "transitions_from": [
                {
                    "from_state": "Plant",
                    "to_state": "EXIT_STATE",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": null
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Plant",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": null
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Worker",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Plant"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Worker",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Plant"
                }
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Plant",
                "Plant.Worker",
                "Plant.Worker.Idle",
                "Plant.Worker.Failed",
                "Plant.Worker.Halted",
                "Plant.Bus"
            ]
        },
        "Plant.Worker": {
            "name": "Worker",
            "path": [
                "Plant",
                "Worker"
            ],
            "parent": "Plant",
            "substates": [
                "Idle",
                "Failed",
                "Halted"
            ],
            "events": {},
            "transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Plant.Worker"
                },
                {
                    "from_state": "Idle",
                    "to_state": "Failed",
                    "event": "Plant.GlobalFault",
                    "guard": null,
                    "effects": [],
                    "parent": "Plant.Worker"
                },
                {
                    "from_state": "Failed",
                    "to_state": "Halted",
                    "event": "Plant.Bus.Stop",
                    "guard": null,
                    "effects": [],
                    "parent": "Plant.Worker"
                },
                {
                    "from_state": "Halted",
                    "to_state": "Idle",
                    "event": "Plant.Bus.Reset",
                    "guard": null,
                    "effects": [],
                    "parent": "Plant.Worker"
                }
            ],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {
                "Idle": 0,
                "Failed": 1,
                "Halted": 2
            },
            "extra_name": "Mapped Worker",
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": false,
            "is_stoppable": false,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Plant.Worker"
                }
            ],
            "transitions_from": [],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Worker",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Plant"
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Plant.Worker"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Plant.Worker"
                }
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Plant.Worker",
                "Plant.Worker.Idle",
                "Plant.Worker.Failed",
                "Plant.Worker.Halted"
            ]
        },
        "Plant.Worker.Idle": {
            "name": "Idle",
            "path": [
                "Plant",
                "Worker",
                "Idle"
            ],
            "parent": "Plant.Worker",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "Idle",
                    "to_state": "Failed",
                    "event": "Plant.GlobalFault",
                    "guard": null,
                    "effects": [],
                    "parent": "Plant.Worker"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Plant.Worker"
                },
                {
                    "from_state": "Halted",
                    "to_state": "Idle",
                    "event": "Plant.Bus.Reset",
                    "guard": null,
                    "effects": [],
                    "parent": "Plant.Worker"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Plant.Worker.Idle"
            ]
        },
        "Plant.Worker.Failed": {
            "name": "Failed",
            "path": [
                "Plant",
                "Worker",
                "Failed"
            ],
            "parent": "Plant.Worker",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "Failed",
                    "to_state": "Halted",
                    "event": "Plant.Bus.Stop",
                    "guard": null,
                    "effects": [],
                    "parent": "Plant.Worker"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "Idle",
                    "to_state": "Failed",
                    "event": "Plant.GlobalFault",
                    "guard": null,
                    "effects": [],
                    "parent": "Plant.Worker"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Plant.Worker.Failed"
            ]
        },
        "Plant.Worker.Halted": {
            "name": "Halted",
            "path": [
                "Plant",
                "Worker",
                "Halted"
            ],
            "parent": "Plant.Worker",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "Halted",
                    "to_state": "Idle",
                    "event": "Plant.Bus.Reset",
                    "guard": null,
                    "effects": [],
                    "parent": "Plant.Worker"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "Failed",
                    "to_state": "Halted",
                    "event": "Plant.Bus.Stop",
                    "guard": null,
                    "effects": [],
                    "parent": "Plant.Worker"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Plant.Worker.Halted"
            ]
        },
        "Plant.Bus": {
            "name": "Bus",
            "path": [
                "Plant",
                "Bus"
            ],
            "parent": "Plant",
            "substates": [],
            "events": {
                "Reset": {
                    "name": "Reset",
                    "state_path": [
                        "Plant",
                        "Bus"
                    ],
                    "path": [
                        "Plant",
                        "Bus",
                        "Reset"
                    ],
                    "path_name": "Plant.Bus.Reset",
                    "extra_name": "Local Reset"
                },
                "Stop": {
                    "name": "Stop",
                    "state_path": [
                        "Plant",
                        "Bus"
                    ],
                    "path": [
                        "Plant",
                        "Bus",
                        "Stop"
                    ],
                    "path_name": "Plant.Bus.Stop",
                    "extra_name": "Plant Stop"
                }
            },
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [],
            "transitions_to": [],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Plant.Bus"
            ]
        }
    },
    "ast": {
        "__class__": "StateMachineDSLProgram",
        "definitions": [],
        "root_state": {
            "__class__": "StateDefinition",
            "name": "Plant",
            "extra_name": null,
            "events": [
                {
                    "__class__": "EventDefinition",
                    "name": "GlobalFault",
                    "extra_name": "Global Fault"
                }
            ],
            "substates": [
                {
                    "__class__": "StateDefinition",
                    "name": "Worker",
                    "extra_name": "Mapped Worker",
                    "events": [],
                    "substates": [
                        {
                            "__class__": "StateDefinition",
                            "name": "Idle",
                            "extra_name": null,
                            "events": [],
                            "substates": [],
                            "transitions": [],
                            "enters": [],
                            "durings": [],
                            "exits": [],
                            "during_aspects": [],
                            "is_pseudo": false
                        },
                        {
                            "__class__": "StateDefinition",
                            "name": "Failed",
                            "extra_name": null,
                            "events": [],
                            "substates": [],
                            "transitions": [],
                            "enters": [],
                            "durings": [],
                            "exits": [],
                            "during_aspects": [],
                            "is_pseudo": false
                        },
                        {
                            "__class__": "StateDefinition",
                            "name": "Halted",
                            "extra_name": null,
                            "events": [],
                            "substates": [],
                            "transitions": [],
                            "enters": [],
                            "durings": [],
                            "exits": [],
                            "during_aspects": [],
                            "is_pseudo": false
                        }
                    ],
                    "transitions": [
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "INIT_STATE",
                            "to_state": "Idle",
                            "event_id": null,
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Idle",
                            "to_state": "Failed",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "GlobalFault"
                                ],
                                "is_absolute": true
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Failed",
                            "to_state": "Halted",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "Bus",
                                    "Stop"
                                ],
                                "is_absolute": true
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Halted",
                            "to_state": "Idle",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "Bus",
                                    "Reset"
                                ],
                                "is_absolute": true
                            },
                            "condition_expr": null,
                            "post_operations": []
                        }
                    ],
                    "enters": [],
                    "durings": [],
                    "exits": [],
                    "during_aspects": [],
                    "is_pseudo": false
                },
                {
                    "__class__": "StateDefinition",
                    "name": "Bus",
                    "extra_name": null,
                    "events": [
                        {
                            "__class__": "EventDefinition",
                            "name": "Stop",
                            "extra_name": "Plant Stop"
                        },
                        {
                            "__class__": "EventDefinition",
                            "name": "Reset",
                            "extra_name": "Local Reset"
                        }
                    ],
                    "substates": [],
                    "transitions": [],
                    "enters": [],
                    "durings": [],
                    "exits": [],
                    "during_aspects": [],
                    "is_pseudo": false
                }
            ],
            "transitions": [
                {
                    "__class__": "TransitionDefinition",
                    "from_state": "INIT_STATE",
                    "to_state": "Worker",
                    "event_id": null,
                    "condition_expr": null,
                    "post_operations": []
                }
            ],
            "enters": [],
            "durings": [],
            "exits": [],
            "during_aspects": [],
            "is_pseudo": false
        }
    }
},
});
