// Generated by scripts/generate_model_sample_tests.py. Do not edit manually.
import {runPyGeneratedModelCase} from "./support";

runPyGeneratedModelCase({
    name: "import_phase3_default_dual_motors",
    relativeSourcePath: "import_phase3_default_dual_motors",
    source: null,
    files: [
    [
        "main.fcstm",
        "state Fleet {\n    import \"./modules/motor.fcstm\" as LeftMotor;\n    import \"./modules/motor.fcstm\" as RightMotor;\n    [*] -> LeftMotor;\n    LeftMotor -> RightMotor;\n}\n"
    ],
    [
        "modules/motor.fcstm",
        "def int counter = 0;\ndef int limit = 3;\n\nstate MotorRoot {\n    state Idle;\n    state Running;\n    [*] -> Idle;\n    Idle -> Running : if [counter < limit] effect {\n        counter = counter + 1;\n    }\n    Running -> Idle : if [counter >= limit] effect {\n        counter = 0;\n    }\n}\n"
    ]
],
    entryFile: "main.fcstm",
    expected: {
    "defines": {
        "LeftMotor_counter": {
            "type": "int",
            "init": {
                "type": "Integer",
                "value": 0
            }
        },
        "LeftMotor_limit": {
            "type": "int",
            "init": {
                "type": "Integer",
                "value": 3
            }
        },
        "RightMotor_counter": {
            "type": "int",
            "init": {
                "type": "Integer",
                "value": 0
            }
        },
        "RightMotor_limit": {
            "type": "int",
            "init": {
                "type": "Integer",
                "value": 3
            }
        }
    },
    "root_state": "Fleet",
    "walk_states": [
        "Fleet",
        "Fleet.LeftMotor",
        "Fleet.LeftMotor.Idle",
        "Fleet.LeftMotor.Running",
        "Fleet.RightMotor",
        "Fleet.RightMotor.Idle",
        "Fleet.RightMotor.Running"
    ],
    "all_events": [],
    "all_actions": [],
    "states": {
        "Fleet": {
            "name": "Fleet",
            "path": [
                "Fleet"
            ],
            "parent": null,
            "substates": [
                "LeftMotor",
                "RightMotor"
            ],
            "events": {},
            "transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LeftMotor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet"
                },
                {
                    "from_state": "LeftMotor",
                    "to_state": "RightMotor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet"
                }
            ],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {
                "LeftMotor": 0,
                "RightMotor": 1
            },
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": true,
            "is_stoppable": false,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LeftMotor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet"
                }
            ],
            "transitions_from": [
                {
                    "from_state": "Fleet",
                    "to_state": "EXIT_STATE",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": null
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Fleet",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": null
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LeftMotor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LeftMotor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet"
                }
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Fleet",
                "Fleet.LeftMotor",
                "Fleet.LeftMotor.Idle",
                "Fleet.LeftMotor.Running",
                "Fleet.RightMotor",
                "Fleet.RightMotor.Idle",
                "Fleet.RightMotor.Running"
            ]
        },
        "Fleet.LeftMotor": {
            "name": "LeftMotor",
            "path": [
                "Fleet",
                "LeftMotor"
            ],
            "parent": "Fleet",
            "substates": [
                "Idle",
                "Running"
            ],
            "events": {},
            "transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                },
                {
                    "from_state": "Idle",
                    "to_state": "Running",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": "<",
                        "x": {
                            "type": "Variable",
                            "name": "LeftMotor_counter"
                        },
                        "y": {
                            "type": "Variable",
                            "name": "LeftMotor_limit"
                        }
                    },
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "LeftMotor_counter",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "LeftMotor_counter"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        }
                    ],
                    "parent": "Fleet.LeftMotor"
                },
                {
                    "from_state": "Running",
                    "to_state": "Idle",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": ">=",
                        "x": {
                            "type": "Variable",
                            "name": "LeftMotor_counter"
                        },
                        "y": {
                            "type": "Variable",
                            "name": "LeftMotor_limit"
                        }
                    },
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "LeftMotor_counter",
                            "expr": {
                                "type": "Integer",
                                "value": 0
                            }
                        }
                    ],
                    "parent": "Fleet.LeftMotor"
                }
            ],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {
                "Idle": 0,
                "Running": 1
            },
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": false,
            "is_stoppable": false,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                }
            ],
            "transitions_from": [
                {
                    "from_state": "LeftMotor",
                    "to_state": "RightMotor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LeftMotor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet"
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                }
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Fleet.LeftMotor",
                "Fleet.LeftMotor.Idle",
                "Fleet.LeftMotor.Running"
            ]
        },
        "Fleet.LeftMotor.Idle": {
            "name": "Idle",
            "path": [
                "Fleet",
                "LeftMotor",
                "Idle"
            ],
            "parent": "Fleet.LeftMotor",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "Idle",
                    "to_state": "Running",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": "<",
                        "x": {
                            "type": "Variable",
                            "name": "LeftMotor_counter"
                        },
                        "y": {
                            "type": "Variable",
                            "name": "LeftMotor_limit"
                        }
                    },
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "LeftMotor_counter",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "LeftMotor_counter"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        }
                    ],
                    "parent": "Fleet.LeftMotor"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                },
                {
                    "from_state": "Running",
                    "to_state": "Idle",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": ">=",
                        "x": {
                            "type": "Variable",
                            "name": "LeftMotor_counter"
                        },
                        "y": {
                            "type": "Variable",
                            "name": "LeftMotor_limit"
                        }
                    },
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "LeftMotor_counter",
                            "expr": {
                                "type": "Integer",
                                "value": 0
                            }
                        }
                    ],
                    "parent": "Fleet.LeftMotor"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Fleet.LeftMotor.Idle"
            ]
        },
        "Fleet.LeftMotor.Running": {
            "name": "Running",
            "path": [
                "Fleet",
                "LeftMotor",
                "Running"
            ],
            "parent": "Fleet.LeftMotor",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "Running",
                    "to_state": "Idle",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": ">=",
                        "x": {
                            "type": "Variable",
                            "name": "LeftMotor_counter"
                        },
                        "y": {
                            "type": "Variable",
                            "name": "LeftMotor_limit"
                        }
                    },
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "LeftMotor_counter",
                            "expr": {
                                "type": "Integer",
                                "value": 0
                            }
                        }
                    ],
                    "parent": "Fleet.LeftMotor"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "Idle",
                    "to_state": "Running",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": "<",
                        "x": {
                            "type": "Variable",
                            "name": "LeftMotor_counter"
                        },
                        "y": {
                            "type": "Variable",
                            "name": "LeftMotor_limit"
                        }
                    },
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "LeftMotor_counter",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "LeftMotor_counter"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        }
                    ],
                    "parent": "Fleet.LeftMotor"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Fleet.LeftMotor.Running"
            ]
        },
        "Fleet.RightMotor": {
            "name": "RightMotor",
            "path": [
                "Fleet",
                "RightMotor"
            ],
            "parent": "Fleet",
            "substates": [
                "Idle",
                "Running"
            ],
            "events": {},
            "transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                },
                {
                    "from_state": "Idle",
                    "to_state": "Running",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": "<",
                        "x": {
                            "type": "Variable",
                            "name": "RightMotor_counter"
                        },
                        "y": {
                            "type": "Variable",
                            "name": "RightMotor_limit"
                        }
                    },
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "RightMotor_counter",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "RightMotor_counter"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        }
                    ],
                    "parent": "Fleet.RightMotor"
                },
                {
                    "from_state": "Running",
                    "to_state": "Idle",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": ">=",
                        "x": {
                            "type": "Variable",
                            "name": "RightMotor_counter"
                        },
                        "y": {
                            "type": "Variable",
                            "name": "RightMotor_limit"
                        }
                    },
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "RightMotor_counter",
                            "expr": {
                                "type": "Integer",
                                "value": 0
                            }
                        }
                    ],
                    "parent": "Fleet.RightMotor"
                }
            ],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {
                "Idle": 0,
                "Running": 1
            },
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": false,
            "is_stoppable": false,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                }
            ],
            "transitions_from": [],
            "transitions_to": [
                {
                    "from_state": "LeftMotor",
                    "to_state": "RightMotor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet"
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                }
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Fleet.RightMotor",
                "Fleet.RightMotor.Idle",
                "Fleet.RightMotor.Running"
            ]
        },
        "Fleet.RightMotor.Idle": {
            "name": "Idle",
            "path": [
                "Fleet",
                "RightMotor",
                "Idle"
            ],
            "parent": "Fleet.RightMotor",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "Idle",
                    "to_state": "Running",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": "<",
                        "x": {
                            "type": "Variable",
                            "name": "RightMotor_counter"
                        },
                        "y": {
                            "type": "Variable",
                            "name": "RightMotor_limit"
                        }
                    },
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "RightMotor_counter",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "RightMotor_counter"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        }
                    ],
                    "parent": "Fleet.RightMotor"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                },
                {
                    "from_state": "Running",
                    "to_state": "Idle",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": ">=",
                        "x": {
                            "type": "Variable",
                            "name": "RightMotor_counter"
                        },
                        "y": {
                            "type": "Variable",
                            "name": "RightMotor_limit"
                        }
                    },
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "RightMotor_counter",
                            "expr": {
                                "type": "Integer",
                                "value": 0
                            }
                        }
                    ],
                    "parent": "Fleet.RightMotor"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Fleet.RightMotor.Idle"
            ]
        },
        "Fleet.RightMotor.Running": {
            "name": "Running",
            "path": [
                "Fleet",
                "RightMotor",
                "Running"
            ],
            "parent": "Fleet.RightMotor",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "Running",
                    "to_state": "Idle",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": ">=",
                        "x": {
                            "type": "Variable",
                            "name": "RightMotor_counter"
                        },
                        "y": {
                            "type": "Variable",
                            "name": "RightMotor_limit"
                        }
                    },
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "RightMotor_counter",
                            "expr": {
                                "type": "Integer",
                                "value": 0
                            }
                        }
                    ],
                    "parent": "Fleet.RightMotor"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "Idle",
                    "to_state": "Running",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": "<",
                        "x": {
                            "type": "Variable",
                            "name": "RightMotor_counter"
                        },
                        "y": {
                            "type": "Variable",
                            "name": "RightMotor_limit"
                        }
                    },
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "RightMotor_counter",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "RightMotor_counter"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        }
                    ],
                    "parent": "Fleet.RightMotor"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Fleet.RightMotor.Running"
            ]
        }
    },
    "ast": {
        "__class__": "StateMachineDSLProgram",
        "definitions": [
            {
                "__class__": "DefAssignment",
                "name": "LeftMotor_counter",
                "type": "int",
                "expr": {
                    "__class__": "Integer",
                    "raw": "0"
                }
            },
            {
                "__class__": "DefAssignment",
                "name": "LeftMotor_limit",
                "type": "int",
                "expr": {
                    "__class__": "Integer",
                    "raw": "3"
                }
            },
            {
                "__class__": "DefAssignment",
                "name": "RightMotor_counter",
                "type": "int",
                "expr": {
                    "__class__": "Integer",
                    "raw": "0"
                }
            },
            {
                "__class__": "DefAssignment",
                "name": "RightMotor_limit",
                "type": "int",
                "expr": {
                    "__class__": "Integer",
                    "raw": "3"
                }
            }
        ],
        "root_state": {
            "__class__": "StateDefinition",
            "name": "Fleet",
            "extra_name": null,
            "events": [],
            "substates": [
                {
                    "__class__": "StateDefinition",
                    "name": "LeftMotor",
                    "extra_name": null,
                    "events": [],
                    "substates": [
                        {
                            "__class__": "StateDefinition",
                            "name": "Idle",
                            "extra_name": null,
                            "events": [],
                            "substates": [],
                            "transitions": [],
                            "enters": [],
                            "durings": [],
                            "exits": [],
                            "during_aspects": [],
                            "is_pseudo": false
                        },
                        {
                            "__class__": "StateDefinition",
                            "name": "Running",
                            "extra_name": null,
                            "events": [],
                            "substates": [],
                            "transitions": [],
                            "enters": [],
                            "durings": [],
                            "exits": [],
                            "during_aspects": [],
                            "is_pseudo": false
                        }
                    ],
                    "transitions": [
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "INIT_STATE",
                            "to_state": "Idle",
                            "event_id": null,
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Idle",
                            "to_state": "Running",
                            "event_id": null,
                            "condition_expr": {
                                "__class__": "BinaryOp",
                                "expr1": {
                                    "__class__": "Name",
                                    "name": "LeftMotor_counter"
                                },
                                "op": "<",
                                "expr2": {
                                    "__class__": "Name",
                                    "name": "LeftMotor_limit"
                                }
                            },
                            "post_operations": [
                                {
                                    "__class__": "OperationAssignment",
                                    "name": "LeftMotor_counter",
                                    "expr": {
                                        "__class__": "BinaryOp",
                                        "expr1": {
                                            "__class__": "Name",
                                            "name": "LeftMotor_counter"
                                        },
                                        "op": "+",
                                        "expr2": {
                                            "__class__": "Integer",
                                            "raw": "1"
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Running",
                            "to_state": "Idle",
                            "event_id": null,
                            "condition_expr": {
                                "__class__": "BinaryOp",
                                "expr1": {
                                    "__class__": "Name",
                                    "name": "LeftMotor_counter"
                                },
                                "op": ">=",
                                "expr2": {
                                    "__class__": "Name",
                                    "name": "LeftMotor_limit"
                                }
                            },
                            "post_operations": [
                                {
                                    "__class__": "OperationAssignment",
                                    "name": "LeftMotor_counter",
                                    "expr": {
                                        "__class__": "Integer",
                                        "raw": "0"
                                    }
                                }
                            ]
                        }
                    ],
                    "enters": [],
                    "durings": [],
                    "exits": [],
                    "during_aspects": [],
                    "is_pseudo": false
                },
                {
                    "__class__": "StateDefinition",
                    "name": "RightMotor",
                    "extra_name": null,
                    "events": [],
                    "substates": [
                        {
                            "__class__": "StateDefinition",
                            "name": "Idle",
                            "extra_name": null,
                            "events": [],
                            "substates": [],
                            "transitions": [],
                            "enters": [],
                            "durings": [],
                            "exits": [],
                            "during_aspects": [],
                            "is_pseudo": false
                        },
                        {
                            "__class__": "StateDefinition",
                            "name": "Running",
                            "extra_name": null,
                            "events": [],
                            "substates": [],
                            "transitions": [],
                            "enters": [],
                            "durings": [],
                            "exits": [],
                            "during_aspects": [],
                            "is_pseudo": false
                        }
                    ],
                    "transitions": [
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "INIT_STATE",
                            "to_state": "Idle",
                            "event_id": null,
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Idle",
                            "to_state": "Running",
                            "event_id": null,
                            "condition_expr": {
                                "__class__": "BinaryOp",
                                "expr1": {
                                    "__class__": "Name",
                                    "name": "RightMotor_counter"
                                },
                                "op": "<",
                                "expr2": {
                                    "__class__": "Name",
                                    "name": "RightMotor_limit"
                                }
                            },
                            "post_operations": [
                                {
                                    "__class__": "OperationAssignment",
                                    "name": "RightMotor_counter",
                                    "expr": {
                                        "__class__": "BinaryOp",
                                        "expr1": {
                                            "__class__": "Name",
                                            "name": "RightMotor_counter"
                                        },
                                        "op": "+",
                                        "expr2": {
                                            "__class__": "Integer",
                                            "raw": "1"
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Running",
                            "to_state": "Idle",
                            "event_id": null,
                            "condition_expr": {
                                "__class__": "BinaryOp",
                                "expr1": {
                                    "__class__": "Name",
                                    "name": "RightMotor_counter"
                                },
                                "op": ">=",
                                "expr2": {
                                    "__class__": "Name",
                                    "name": "RightMotor_limit"
                                }
                            },
                            "post_operations": [
                                {
                                    "__class__": "OperationAssignment",
                                    "name": "RightMotor_counter",
                                    "expr": {
                                        "__class__": "Integer",
                                        "raw": "0"
                                    }
                                }
                            ]
                        }
                    ],
                    "enters": [],
                    "durings": [],
                    "exits": [],
                    "during_aspects": [],
                    "is_pseudo": false
                }
            ],
            "transitions": [
                {
                    "__class__": "TransitionDefinition",
                    "from_state": "INIT_STATE",
                    "to_state": "LeftMotor",
                    "event_id": null,
                    "condition_expr": null,
                    "post_operations": []
                },
                {
                    "__class__": "TransitionDefinition",
                    "from_state": "LeftMotor",
                    "to_state": "RightMotor",
                    "event_id": null,
                    "condition_expr": null,
                    "post_operations": []
                }
            ],
            "enters": [],
            "durings": [],
            "exits": [],
            "during_aspects": [],
            "is_pseudo": false
        }
    }
},
});
