// Generated by scripts/generate_model_sample_tests.py. Do not edit manually.
import {runPyGeneratedModelCase} from "./support";

runPyGeneratedModelCase({
    name: "import_phase4_shared_event_bus",
    relativeSourcePath: "import_phase4_shared_event_bus",
    source: "state Fleet {\n    state LeftMotor named 'Left Motor' {\n        state Idle;\n        state Running;\n        state Error;\n        Idle -> Error : /Bus.Alarm;\n        Running -> Error : /Bus.Alarm;\n        Error -> Error : /Bus.Alarm;\n        [*] -> Idle;\n        Idle -> Running : /Start;\n        Running -> Idle : /Bus.Stop;\n    }\n    state RightMotor named 'Right Motor' {\n        state Idle;\n        state Running;\n        state Error;\n        Idle -> Error : /Bus.Alarm;\n        Running -> Error : /Bus.Alarm;\n        Error -> Error : /Bus.Alarm;\n        [*] -> Idle;\n        Idle -> Running : /Start;\n        Running -> Idle : /Bus.Stop;\n    }\n    state Bus {\n        event Stop;\n        event Alarm named 'Fleet Alarm';\n    }\n    event Start named 'Fleet Start';\n    [*] -> LeftMotor;\n    LeftMotor -> RightMotor;\n}",
    files: [
    [
        "main.fcstm",
        "state Fleet {\n    state Bus;\n    import \"./modules/motor.fcstm\" as LeftMotor named \"Left Motor\" {\n        event /Start -> Start named \"Fleet Start\";\n        event /Stop -> /Bus.Stop;\n        event /Alarm -> /Bus.Alarm named \"Fleet Alarm\";\n    }\n    import \"./modules/motor.fcstm\" as RightMotor named \"Right Motor\" {\n        event /Start -> Start named \"Fleet Start\";\n        event /Stop -> /Bus.Stop;\n        event /Alarm -> /Bus.Alarm named \"Fleet Alarm\";\n    }\n    [*] -> LeftMotor;\n    LeftMotor -> RightMotor;\n}\n"
    ],
    [
        "modules/motor.fcstm",
        "state MotorRoot {\n    event Alarm named \"Local Alarm\";\n    state Idle;\n    state Running;\n    state Error;\n    [*] -> Idle;\n    Idle -> Running : /Start;\n    Running -> Idle : /Stop;\n    ! * -> Error : Alarm;\n}\n"
    ]
],
    entryFile: "main.fcstm",
    expected: {
    "defines": {},
    "root_state": "Fleet",
    "walk_states": [
        "Fleet",
        "Fleet.LeftMotor",
        "Fleet.LeftMotor.Idle",
        "Fleet.LeftMotor.Running",
        "Fleet.LeftMotor.Error",
        "Fleet.RightMotor",
        "Fleet.RightMotor.Idle",
        "Fleet.RightMotor.Running",
        "Fleet.RightMotor.Error",
        "Fleet.Bus"
    ],
    "all_events": [
        {
            "name": "Start",
            "state_path": [
                "Fleet"
            ],
            "path": [
                "Fleet",
                "Start"
            ],
            "path_name": "Fleet.Start",
            "extra_name": "Fleet Start"
        },
        {
            "name": "Stop",
            "state_path": [
                "Fleet",
                "Bus"
            ],
            "path": [
                "Fleet",
                "Bus",
                "Stop"
            ],
            "path_name": "Fleet.Bus.Stop",
            "extra_name": null
        },
        {
            "name": "Alarm",
            "state_path": [
                "Fleet",
                "Bus"
            ],
            "path": [
                "Fleet",
                "Bus",
                "Alarm"
            ],
            "path_name": "Fleet.Bus.Alarm",
            "extra_name": "Fleet Alarm"
        }
    ],
    "all_actions": [],
    "states": {
        "Fleet": {
            "name": "Fleet",
            "path": [
                "Fleet"
            ],
            "parent": null,
            "substates": [
                "LeftMotor",
                "RightMotor",
                "Bus"
            ],
            "events": {
                "Start": {
                    "name": "Start",
                    "state_path": [
                        "Fleet"
                    ],
                    "path": [
                        "Fleet",
                        "Start"
                    ],
                    "path_name": "Fleet.Start",
                    "extra_name": "Fleet Start"
                }
            },
            "transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LeftMotor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet"
                },
                {
                    "from_state": "LeftMotor",
                    "to_state": "RightMotor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet"
                }
            ],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {
                "LeftMotor": 0,
                "RightMotor": 1,
                "Bus": 2
            },
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": true,
            "is_stoppable": false,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LeftMotor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet"
                }
            ],
            "transitions_from": [
                {
                    "from_state": "Fleet",
                    "to_state": "EXIT_STATE",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": null
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Fleet",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": null
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LeftMotor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LeftMotor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet"
                }
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Fleet",
                "Fleet.LeftMotor",
                "Fleet.LeftMotor.Idle",
                "Fleet.LeftMotor.Running",
                "Fleet.LeftMotor.Error",
                "Fleet.RightMotor",
                "Fleet.RightMotor.Idle",
                "Fleet.RightMotor.Running",
                "Fleet.RightMotor.Error",
                "Fleet.Bus"
            ]
        },
        "Fleet.LeftMotor": {
            "name": "LeftMotor",
            "path": [
                "Fleet",
                "LeftMotor"
            ],
            "parent": "Fleet",
            "substates": [
                "Idle",
                "Running",
                "Error"
            ],
            "events": {},
            "transitions": [
                {
                    "from_state": "Idle",
                    "to_state": "Error",
                    "event": "Fleet.Bus.Alarm",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                },
                {
                    "from_state": "Running",
                    "to_state": "Error",
                    "event": "Fleet.Bus.Alarm",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                },
                {
                    "from_state": "Error",
                    "to_state": "Error",
                    "event": "Fleet.Bus.Alarm",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                },
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                },
                {
                    "from_state": "Idle",
                    "to_state": "Running",
                    "event": "Fleet.Start",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                },
                {
                    "from_state": "Running",
                    "to_state": "Idle",
                    "event": "Fleet.Bus.Stop",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                }
            ],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {
                "Idle": 0,
                "Running": 1,
                "Error": 2
            },
            "extra_name": "Left Motor",
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": false,
            "is_stoppable": false,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                }
            ],
            "transitions_from": [
                {
                    "from_state": "LeftMotor",
                    "to_state": "RightMotor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "LeftMotor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet"
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                }
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Fleet.LeftMotor",
                "Fleet.LeftMotor.Idle",
                "Fleet.LeftMotor.Running",
                "Fleet.LeftMotor.Error"
            ]
        },
        "Fleet.LeftMotor.Idle": {
            "name": "Idle",
            "path": [
                "Fleet",
                "LeftMotor",
                "Idle"
            ],
            "parent": "Fleet.LeftMotor",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "Idle",
                    "to_state": "Error",
                    "event": "Fleet.Bus.Alarm",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                },
                {
                    "from_state": "Idle",
                    "to_state": "Running",
                    "event": "Fleet.Start",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                },
                {
                    "from_state": "Running",
                    "to_state": "Idle",
                    "event": "Fleet.Bus.Stop",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Fleet.LeftMotor.Idle"
            ]
        },
        "Fleet.LeftMotor.Running": {
            "name": "Running",
            "path": [
                "Fleet",
                "LeftMotor",
                "Running"
            ],
            "parent": "Fleet.LeftMotor",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "Running",
                    "to_state": "Error",
                    "event": "Fleet.Bus.Alarm",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                },
                {
                    "from_state": "Running",
                    "to_state": "Idle",
                    "event": "Fleet.Bus.Stop",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "Idle",
                    "to_state": "Running",
                    "event": "Fleet.Start",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Fleet.LeftMotor.Running"
            ]
        },
        "Fleet.LeftMotor.Error": {
            "name": "Error",
            "path": [
                "Fleet",
                "LeftMotor",
                "Error"
            ],
            "parent": "Fleet.LeftMotor",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "Error",
                    "to_state": "Error",
                    "event": "Fleet.Bus.Alarm",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "Idle",
                    "to_state": "Error",
                    "event": "Fleet.Bus.Alarm",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                },
                {
                    "from_state": "Running",
                    "to_state": "Error",
                    "event": "Fleet.Bus.Alarm",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                },
                {
                    "from_state": "Error",
                    "to_state": "Error",
                    "event": "Fleet.Bus.Alarm",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.LeftMotor"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Fleet.LeftMotor.Error"
            ]
        },
        "Fleet.RightMotor": {
            "name": "RightMotor",
            "path": [
                "Fleet",
                "RightMotor"
            ],
            "parent": "Fleet",
            "substates": [
                "Idle",
                "Running",
                "Error"
            ],
            "events": {},
            "transitions": [
                {
                    "from_state": "Idle",
                    "to_state": "Error",
                    "event": "Fleet.Bus.Alarm",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                },
                {
                    "from_state": "Running",
                    "to_state": "Error",
                    "event": "Fleet.Bus.Alarm",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                },
                {
                    "from_state": "Error",
                    "to_state": "Error",
                    "event": "Fleet.Bus.Alarm",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                },
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                },
                {
                    "from_state": "Idle",
                    "to_state": "Running",
                    "event": "Fleet.Start",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                },
                {
                    "from_state": "Running",
                    "to_state": "Idle",
                    "event": "Fleet.Bus.Stop",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                }
            ],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {
                "Idle": 0,
                "Running": 1,
                "Error": 2
            },
            "extra_name": "Right Motor",
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": false,
            "is_stoppable": false,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                }
            ],
            "transitions_from": [],
            "transitions_to": [
                {
                    "from_state": "LeftMotor",
                    "to_state": "RightMotor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet"
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                }
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Fleet.RightMotor",
                "Fleet.RightMotor.Idle",
                "Fleet.RightMotor.Running",
                "Fleet.RightMotor.Error"
            ]
        },
        "Fleet.RightMotor.Idle": {
            "name": "Idle",
            "path": [
                "Fleet",
                "RightMotor",
                "Idle"
            ],
            "parent": "Fleet.RightMotor",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "Idle",
                    "to_state": "Error",
                    "event": "Fleet.Bus.Alarm",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                },
                {
                    "from_state": "Idle",
                    "to_state": "Running",
                    "event": "Fleet.Start",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Idle",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                },
                {
                    "from_state": "Running",
                    "to_state": "Idle",
                    "event": "Fleet.Bus.Stop",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Fleet.RightMotor.Idle"
            ]
        },
        "Fleet.RightMotor.Running": {
            "name": "Running",
            "path": [
                "Fleet",
                "RightMotor",
                "Running"
            ],
            "parent": "Fleet.RightMotor",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "Running",
                    "to_state": "Error",
                    "event": "Fleet.Bus.Alarm",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                },
                {
                    "from_state": "Running",
                    "to_state": "Idle",
                    "event": "Fleet.Bus.Stop",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "Idle",
                    "to_state": "Running",
                    "event": "Fleet.Start",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Fleet.RightMotor.Running"
            ]
        },
        "Fleet.RightMotor.Error": {
            "name": "Error",
            "path": [
                "Fleet",
                "RightMotor",
                "Error"
            ],
            "parent": "Fleet.RightMotor",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "Error",
                    "to_state": "Error",
                    "event": "Fleet.Bus.Alarm",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "Idle",
                    "to_state": "Error",
                    "event": "Fleet.Bus.Alarm",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                },
                {
                    "from_state": "Running",
                    "to_state": "Error",
                    "event": "Fleet.Bus.Alarm",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                },
                {
                    "from_state": "Error",
                    "to_state": "Error",
                    "event": "Fleet.Bus.Alarm",
                    "guard": null,
                    "effects": [],
                    "parent": "Fleet.RightMotor"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Fleet.RightMotor.Error"
            ]
        },
        "Fleet.Bus": {
            "name": "Bus",
            "path": [
                "Fleet",
                "Bus"
            ],
            "parent": "Fleet",
            "substates": [],
            "events": {
                "Alarm": {
                    "name": "Alarm",
                    "state_path": [
                        "Fleet",
                        "Bus"
                    ],
                    "path": [
                        "Fleet",
                        "Bus",
                        "Alarm"
                    ],
                    "path_name": "Fleet.Bus.Alarm",
                    "extra_name": "Fleet Alarm"
                },
                "Stop": {
                    "name": "Stop",
                    "state_path": [
                        "Fleet",
                        "Bus"
                    ],
                    "path": [
                        "Fleet",
                        "Bus",
                        "Stop"
                    ],
                    "path_name": "Fleet.Bus.Stop",
                    "extra_name": null
                }
            },
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [],
            "transitions_to": [],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Fleet.Bus"
            ]
        }
    },
    "ast": {
        "__class__": "StateMachineDSLProgram",
        "definitions": [],
        "root_state": {
            "__class__": "StateDefinition",
            "name": "Fleet",
            "extra_name": null,
            "events": [
                {
                    "__class__": "EventDefinition",
                    "name": "Start",
                    "extra_name": "Fleet Start"
                }
            ],
            "substates": [
                {
                    "__class__": "StateDefinition",
                    "name": "LeftMotor",
                    "extra_name": "Left Motor",
                    "events": [],
                    "substates": [
                        {
                            "__class__": "StateDefinition",
                            "name": "Idle",
                            "extra_name": null,
                            "events": [],
                            "substates": [],
                            "transitions": [],
                            "enters": [],
                            "durings": [],
                            "exits": [],
                            "during_aspects": [],
                            "is_pseudo": false
                        },
                        {
                            "__class__": "StateDefinition",
                            "name": "Running",
                            "extra_name": null,
                            "events": [],
                            "substates": [],
                            "transitions": [],
                            "enters": [],
                            "durings": [],
                            "exits": [],
                            "during_aspects": [],
                            "is_pseudo": false
                        },
                        {
                            "__class__": "StateDefinition",
                            "name": "Error",
                            "extra_name": null,
                            "events": [],
                            "substates": [],
                            "transitions": [],
                            "enters": [],
                            "durings": [],
                            "exits": [],
                            "during_aspects": [],
                            "is_pseudo": false
                        }
                    ],
                    "transitions": [
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Idle",
                            "to_state": "Error",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "Bus",
                                    "Alarm"
                                ],
                                "is_absolute": true
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Running",
                            "to_state": "Error",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "Bus",
                                    "Alarm"
                                ],
                                "is_absolute": true
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Error",
                            "to_state": "Error",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "Bus",
                                    "Alarm"
                                ],
                                "is_absolute": true
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "INIT_STATE",
                            "to_state": "Idle",
                            "event_id": null,
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Idle",
                            "to_state": "Running",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "Start"
                                ],
                                "is_absolute": true
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Running",
                            "to_state": "Idle",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "Bus",
                                    "Stop"
                                ],
                                "is_absolute": true
                            },
                            "condition_expr": null,
                            "post_operations": []
                        }
                    ],
                    "enters": [],
                    "durings": [],
                    "exits": [],
                    "during_aspects": [],
                    "is_pseudo": false
                },
                {
                    "__class__": "StateDefinition",
                    "name": "RightMotor",
                    "extra_name": "Right Motor",
                    "events": [],
                    "substates": [
                        {
                            "__class__": "StateDefinition",
                            "name": "Idle",
                            "extra_name": null,
                            "events": [],
                            "substates": [],
                            "transitions": [],
                            "enters": [],
                            "durings": [],
                            "exits": [],
                            "during_aspects": [],
                            "is_pseudo": false
                        },
                        {
                            "__class__": "StateDefinition",
                            "name": "Running",
                            "extra_name": null,
                            "events": [],
                            "substates": [],
                            "transitions": [],
                            "enters": [],
                            "durings": [],
                            "exits": [],
                            "during_aspects": [],
                            "is_pseudo": false
                        },
                        {
                            "__class__": "StateDefinition",
                            "name": "Error",
                            "extra_name": null,
                            "events": [],
                            "substates": [],
                            "transitions": [],
                            "enters": [],
                            "durings": [],
                            "exits": [],
                            "during_aspects": [],
                            "is_pseudo": false
                        }
                    ],
                    "transitions": [
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Idle",
                            "to_state": "Error",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "Bus",
                                    "Alarm"
                                ],
                                "is_absolute": true
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Running",
                            "to_state": "Error",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "Bus",
                                    "Alarm"
                                ],
                                "is_absolute": true
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Error",
                            "to_state": "Error",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "Bus",
                                    "Alarm"
                                ],
                                "is_absolute": true
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "INIT_STATE",
                            "to_state": "Idle",
                            "event_id": null,
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Idle",
                            "to_state": "Running",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "Start"
                                ],
                                "is_absolute": true
                            },
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Running",
                            "to_state": "Idle",
                            "event_id": {
                                "__class__": "ChainID",
                                "path": [
                                    "Bus",
                                    "Stop"
                                ],
                                "is_absolute": true
                            },
                            "condition_expr": null,
                            "post_operations": []
                        }
                    ],
                    "enters": [],
                    "durings": [],
                    "exits": [],
                    "during_aspects": [],
                    "is_pseudo": false
                },
                {
                    "__class__": "StateDefinition",
                    "name": "Bus",
                    "extra_name": null,
                    "events": [
                        {
                            "__class__": "EventDefinition",
                            "name": "Stop",
                            "extra_name": null
                        },
                        {
                            "__class__": "EventDefinition",
                            "name": "Alarm",
                            "extra_name": "Fleet Alarm"
                        }
                    ],
                    "substates": [],
                    "transitions": [],
                    "enters": [],
                    "durings": [],
                    "exits": [],
                    "during_aspects": [],
                    "is_pseudo": false
                }
            ],
            "transitions": [
                {
                    "__class__": "TransitionDefinition",
                    "from_state": "INIT_STATE",
                    "to_state": "LeftMotor",
                    "event_id": null,
                    "condition_expr": null,
                    "post_operations": []
                },
                {
                    "__class__": "TransitionDefinition",
                    "from_state": "LeftMotor",
                    "to_state": "RightMotor",
                    "event_id": null,
                    "condition_expr": null,
                    "post_operations": []
                }
            ],
            "enters": [],
            "durings": [],
            "exits": [],
            "during_aspects": [],
            "is_pseudo": false
        }
    }
},
});
