// Generated by scripts/generate_model_sample_tests.py. Do not edit manually.
import {runPyGeneratedModelCase} from "./support";

runPyGeneratedModelCase({
    name: "import_phase3_recursive_line",
    relativeSourcePath: "import_phase3_recursive_line",
    source: null,
    files: [
    [
        "main.fcstm",
        "def int host_ticks = 0;\ndef int host_load = 0;\n\nstate Factory {\n    import \"./modules/line.fcstm\" as Line named \"Assembly Line\" {\n        def line_ticks -> host_ticks;\n        def load -> host_load;\n    }\n    [*] -> Line;\n}\n"
    ],
    [
        "modules/line.fcstm",
        "def int line_ticks = 0;\ndef int load = 0;\n\nstate LineRoot {\n    import \"./subsystems/conveyor.fcstm\" as Conveyor {\n        def speed -> line_ticks;\n        def load -> load;\n    }\n    import \"./subsystems/robot.fcstm\" as Robot {\n        def cycle_count -> line_ticks;\n        def arm_load -> load;\n    }\n    [*] -> Conveyor;\n    Conveyor -> Robot : if [line_ticks >= 2];\n    Robot -> Conveyor : if [load >= 4];\n}\n"
    ],
    [
        "modules/subsystems/conveyor.fcstm",
        "def int speed = 0;\ndef int load = 0;\n\nstate ConveyorRoot {\n    state Feeding;\n    [*] -> Feeding;\n    Feeding -> Feeding : if [speed < 2] effect {\n        speed = speed + 1;\n        load = load + 1;\n    }\n}\n"
    ],
    [
        "modules/subsystems/robot.fcstm",
        "def int cycle_count = 0;\ndef int arm_load = 0;\n\nstate RobotRoot {\n    state Picking;\n    [*] -> Picking;\n    Picking -> Picking : if [arm_load < 4] effect {\n        cycle_count = cycle_count + 1;\n        arm_load = arm_load + 1;\n    }\n}\n"
    ]
],
    entryFile: "main.fcstm",
    expected: {
    "defines": {
        "host_load": {
            "type": "int",
            "init": {
                "type": "Integer",
                "value": 0
            }
        },
        "host_ticks": {
            "type": "int",
            "init": {
                "type": "Integer",
                "value": 0
            }
        }
    },
    "root_state": "Factory",
    "walk_states": [
        "Factory",
        "Factory.Line",
        "Factory.Line.Conveyor",
        "Factory.Line.Conveyor.Feeding",
        "Factory.Line.Robot",
        "Factory.Line.Robot.Picking"
    ],
    "all_events": [],
    "all_actions": [],
    "states": {
        "Factory": {
            "name": "Factory",
            "path": [
                "Factory"
            ],
            "parent": null,
            "substates": [
                "Line"
            ],
            "events": {},
            "transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Line",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Factory"
                }
            ],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {
                "Line": 0
            },
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": true,
            "is_stoppable": false,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Line",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Factory"
                }
            ],
            "transitions_from": [
                {
                    "from_state": "Factory",
                    "to_state": "EXIT_STATE",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": null
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Factory",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": null
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Line",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Factory"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Line",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Factory"
                }
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Factory",
                "Factory.Line",
                "Factory.Line.Conveyor",
                "Factory.Line.Conveyor.Feeding",
                "Factory.Line.Robot",
                "Factory.Line.Robot.Picking"
            ]
        },
        "Factory.Line": {
            "name": "Line",
            "path": [
                "Factory",
                "Line"
            ],
            "parent": "Factory",
            "substates": [
                "Conveyor",
                "Robot"
            ],
            "events": {},
            "transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Conveyor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Factory.Line"
                },
                {
                    "from_state": "Conveyor",
                    "to_state": "Robot",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": ">=",
                        "x": {
                            "type": "Variable",
                            "name": "host_ticks"
                        },
                        "y": {
                            "type": "Integer",
                            "value": 2
                        }
                    },
                    "effects": [],
                    "parent": "Factory.Line"
                },
                {
                    "from_state": "Robot",
                    "to_state": "Conveyor",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": ">=",
                        "x": {
                            "type": "Variable",
                            "name": "host_load"
                        },
                        "y": {
                            "type": "Integer",
                            "value": 4
                        }
                    },
                    "effects": [],
                    "parent": "Factory.Line"
                }
            ],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {
                "Conveyor": 0,
                "Robot": 1
            },
            "extra_name": "Assembly Line",
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": false,
            "is_stoppable": false,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Conveyor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Factory.Line"
                }
            ],
            "transitions_from": [],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Line",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Factory"
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Conveyor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Factory.Line"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Conveyor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Factory.Line"
                }
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Factory.Line",
                "Factory.Line.Conveyor",
                "Factory.Line.Conveyor.Feeding",
                "Factory.Line.Robot",
                "Factory.Line.Robot.Picking"
            ]
        },
        "Factory.Line.Conveyor": {
            "name": "Conveyor",
            "path": [
                "Factory",
                "Line",
                "Conveyor"
            ],
            "parent": "Factory.Line",
            "substates": [
                "Feeding"
            ],
            "events": {},
            "transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Feeding",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Factory.Line.Conveyor"
                },
                {
                    "from_state": "Feeding",
                    "to_state": "Feeding",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": "<",
                        "x": {
                            "type": "Variable",
                            "name": "host_ticks"
                        },
                        "y": {
                            "type": "Integer",
                            "value": 2
                        }
                    },
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "host_ticks",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "host_ticks"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        },
                        {
                            "type": "Operation",
                            "var_name": "host_load",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "host_load"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        }
                    ],
                    "parent": "Factory.Line.Conveyor"
                }
            ],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {
                "Feeding": 0
            },
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": false,
            "is_stoppable": false,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Feeding",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Factory.Line.Conveyor"
                }
            ],
            "transitions_from": [
                {
                    "from_state": "Conveyor",
                    "to_state": "Robot",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": ">=",
                        "x": {
                            "type": "Variable",
                            "name": "host_ticks"
                        },
                        "y": {
                            "type": "Integer",
                            "value": 2
                        }
                    },
                    "effects": [],
                    "parent": "Factory.Line"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Conveyor",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Factory.Line"
                },
                {
                    "from_state": "Robot",
                    "to_state": "Conveyor",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": ">=",
                        "x": {
                            "type": "Variable",
                            "name": "host_load"
                        },
                        "y": {
                            "type": "Integer",
                            "value": 4
                        }
                    },
                    "effects": [],
                    "parent": "Factory.Line"
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Feeding",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Factory.Line.Conveyor"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Feeding",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Factory.Line.Conveyor"
                }
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Factory.Line.Conveyor",
                "Factory.Line.Conveyor.Feeding"
            ]
        },
        "Factory.Line.Conveyor.Feeding": {
            "name": "Feeding",
            "path": [
                "Factory",
                "Line",
                "Conveyor",
                "Feeding"
            ],
            "parent": "Factory.Line.Conveyor",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "Feeding",
                    "to_state": "Feeding",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": "<",
                        "x": {
                            "type": "Variable",
                            "name": "host_ticks"
                        },
                        "y": {
                            "type": "Integer",
                            "value": 2
                        }
                    },
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "host_ticks",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "host_ticks"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        },
                        {
                            "type": "Operation",
                            "var_name": "host_load",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "host_load"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        }
                    ],
                    "parent": "Factory.Line.Conveyor"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Feeding",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Factory.Line.Conveyor"
                },
                {
                    "from_state": "Feeding",
                    "to_state": "Feeding",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": "<",
                        "x": {
                            "type": "Variable",
                            "name": "host_ticks"
                        },
                        "y": {
                            "type": "Integer",
                            "value": 2
                        }
                    },
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "host_ticks",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "host_ticks"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        },
                        {
                            "type": "Operation",
                            "var_name": "host_load",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "host_load"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        }
                    ],
                    "parent": "Factory.Line.Conveyor"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Factory.Line.Conveyor.Feeding"
            ]
        },
        "Factory.Line.Robot": {
            "name": "Robot",
            "path": [
                "Factory",
                "Line",
                "Robot"
            ],
            "parent": "Factory.Line",
            "substates": [
                "Picking"
            ],
            "events": {},
            "transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Picking",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Factory.Line.Robot"
                },
                {
                    "from_state": "Picking",
                    "to_state": "Picking",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": "<",
                        "x": {
                            "type": "Variable",
                            "name": "host_load"
                        },
                        "y": {
                            "type": "Integer",
                            "value": 4
                        }
                    },
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "host_ticks",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "host_ticks"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        },
                        {
                            "type": "Operation",
                            "var_name": "host_load",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "host_load"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        }
                    ],
                    "parent": "Factory.Line.Robot"
                }
            ],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {
                "Picking": 0
            },
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": false,
            "is_stoppable": false,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Picking",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Factory.Line.Robot"
                }
            ],
            "transitions_from": [
                {
                    "from_state": "Robot",
                    "to_state": "Conveyor",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": ">=",
                        "x": {
                            "type": "Variable",
                            "name": "host_load"
                        },
                        "y": {
                            "type": "Integer",
                            "value": 4
                        }
                    },
                    "effects": [],
                    "parent": "Factory.Line"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "Conveyor",
                    "to_state": "Robot",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": ">=",
                        "x": {
                            "type": "Variable",
                            "name": "host_ticks"
                        },
                        "y": {
                            "type": "Integer",
                            "value": 2
                        }
                    },
                    "effects": [],
                    "parent": "Factory.Line"
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Picking",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Factory.Line.Robot"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Picking",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Factory.Line.Robot"
                }
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Factory.Line.Robot",
                "Factory.Line.Robot.Picking"
            ]
        },
        "Factory.Line.Robot.Picking": {
            "name": "Picking",
            "path": [
                "Factory",
                "Line",
                "Robot",
                "Picking"
            ],
            "parent": "Factory.Line.Robot",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {},
            "on_enters": [],
            "on_durings": [],
            "on_exits": [],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "Picking",
                    "to_state": "Picking",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": "<",
                        "x": {
                            "type": "Variable",
                            "name": "host_load"
                        },
                        "y": {
                            "type": "Integer",
                            "value": 4
                        }
                    },
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "host_ticks",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "host_ticks"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        },
                        {
                            "type": "Operation",
                            "var_name": "host_load",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "host_load"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        }
                    ],
                    "parent": "Factory.Line.Robot"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "Picking",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "Factory.Line.Robot"
                },
                {
                    "from_state": "Picking",
                    "to_state": "Picking",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": "<",
                        "x": {
                            "type": "Variable",
                            "name": "host_load"
                        },
                        "y": {
                            "type": "Integer",
                            "value": 4
                        }
                    },
                    "effects": [
                        {
                            "type": "Operation",
                            "var_name": "host_ticks",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "host_ticks"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        },
                        {
                            "type": "Operation",
                            "var_name": "host_load",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "host_load"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        }
                    ],
                    "parent": "Factory.Line.Robot"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [],
            "list_on_enters_with_ids": [],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [],
            "list_on_exits_with_ids": [],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [],
            "list_on_during_aspect_recursively_with_ids": [],
            "walk_states": [
                "Factory.Line.Robot.Picking"
            ]
        }
    },
    "ast": {
        "__class__": "StateMachineDSLProgram",
        "definitions": [
            {
                "__class__": "DefAssignment",
                "name": "host_ticks",
                "type": "int",
                "expr": {
                    "__class__": "Integer",
                    "raw": "0"
                }
            },
            {
                "__class__": "DefAssignment",
                "name": "host_load",
                "type": "int",
                "expr": {
                    "__class__": "Integer",
                    "raw": "0"
                }
            }
        ],
        "root_state": {
            "__class__": "StateDefinition",
            "name": "Factory",
            "extra_name": null,
            "events": [],
            "substates": [
                {
                    "__class__": "StateDefinition",
                    "name": "Line",
                    "extra_name": "Assembly Line",
                    "events": [],
                    "substates": [
                        {
                            "__class__": "StateDefinition",
                            "name": "Conveyor",
                            "extra_name": null,
                            "events": [],
                            "substates": [
                                {
                                    "__class__": "StateDefinition",
                                    "name": "Feeding",
                                    "extra_name": null,
                                    "events": [],
                                    "substates": [],
                                    "transitions": [],
                                    "enters": [],
                                    "durings": [],
                                    "exits": [],
                                    "during_aspects": [],
                                    "is_pseudo": false
                                }
                            ],
                            "transitions": [
                                {
                                    "__class__": "TransitionDefinition",
                                    "from_state": "INIT_STATE",
                                    "to_state": "Feeding",
                                    "event_id": null,
                                    "condition_expr": null,
                                    "post_operations": []
                                },
                                {
                                    "__class__": "TransitionDefinition",
                                    "from_state": "Feeding",
                                    "to_state": "Feeding",
                                    "event_id": null,
                                    "condition_expr": {
                                        "__class__": "BinaryOp",
                                        "expr1": {
                                            "__class__": "Name",
                                            "name": "host_ticks"
                                        },
                                        "op": "<",
                                        "expr2": {
                                            "__class__": "Integer",
                                            "raw": "2"
                                        }
                                    },
                                    "post_operations": [
                                        {
                                            "__class__": "OperationAssignment",
                                            "name": "host_ticks",
                                            "expr": {
                                                "__class__": "BinaryOp",
                                                "expr1": {
                                                    "__class__": "Name",
                                                    "name": "host_ticks"
                                                },
                                                "op": "+",
                                                "expr2": {
                                                    "__class__": "Integer",
                                                    "raw": "1"
                                                }
                                            }
                                        },
                                        {
                                            "__class__": "OperationAssignment",
                                            "name": "host_load",
                                            "expr": {
                                                "__class__": "BinaryOp",
                                                "expr1": {
                                                    "__class__": "Name",
                                                    "name": "host_load"
                                                },
                                                "op": "+",
                                                "expr2": {
                                                    "__class__": "Integer",
                                                    "raw": "1"
                                                }
                                            }
                                        }
                                    ]
                                }
                            ],
                            "enters": [],
                            "durings": [],
                            "exits": [],
                            "during_aspects": [],
                            "is_pseudo": false
                        },
                        {
                            "__class__": "StateDefinition",
                            "name": "Robot",
                            "extra_name": null,
                            "events": [],
                            "substates": [
                                {
                                    "__class__": "StateDefinition",
                                    "name": "Picking",
                                    "extra_name": null,
                                    "events": [],
                                    "substates": [],
                                    "transitions": [],
                                    "enters": [],
                                    "durings": [],
                                    "exits": [],
                                    "during_aspects": [],
                                    "is_pseudo": false
                                }
                            ],
                            "transitions": [
                                {
                                    "__class__": "TransitionDefinition",
                                    "from_state": "INIT_STATE",
                                    "to_state": "Picking",
                                    "event_id": null,
                                    "condition_expr": null,
                                    "post_operations": []
                                },
                                {
                                    "__class__": "TransitionDefinition",
                                    "from_state": "Picking",
                                    "to_state": "Picking",
                                    "event_id": null,
                                    "condition_expr": {
                                        "__class__": "BinaryOp",
                                        "expr1": {
                                            "__class__": "Name",
                                            "name": "host_load"
                                        },
                                        "op": "<",
                                        "expr2": {
                                            "__class__": "Integer",
                                            "raw": "4"
                                        }
                                    },
                                    "post_operations": [
                                        {
                                            "__class__": "OperationAssignment",
                                            "name": "host_ticks",
                                            "expr": {
                                                "__class__": "BinaryOp",
                                                "expr1": {
                                                    "__class__": "Name",
                                                    "name": "host_ticks"
                                                },
                                                "op": "+",
                                                "expr2": {
                                                    "__class__": "Integer",
                                                    "raw": "1"
                                                }
                                            }
                                        },
                                        {
                                            "__class__": "OperationAssignment",
                                            "name": "host_load",
                                            "expr": {
                                                "__class__": "BinaryOp",
                                                "expr1": {
                                                    "__class__": "Name",
                                                    "name": "host_load"
                                                },
                                                "op": "+",
                                                "expr2": {
                                                    "__class__": "Integer",
                                                    "raw": "1"
                                                }
                                            }
                                        }
                                    ]
                                }
                            ],
                            "enters": [],
                            "durings": [],
                            "exits": [],
                            "during_aspects": [],
                            "is_pseudo": false
                        }
                    ],
                    "transitions": [
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "INIT_STATE",
                            "to_state": "Conveyor",
                            "event_id": null,
                            "condition_expr": null,
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Conveyor",
                            "to_state": "Robot",
                            "event_id": null,
                            "condition_expr": {
                                "__class__": "BinaryOp",
                                "expr1": {
                                    "__class__": "Name",
                                    "name": "host_ticks"
                                },
                                "op": ">=",
                                "expr2": {
                                    "__class__": "Integer",
                                    "raw": "2"
                                }
                            },
                            "post_operations": []
                        },
                        {
                            "__class__": "TransitionDefinition",
                            "from_state": "Robot",
                            "to_state": "Conveyor",
                            "event_id": null,
                            "condition_expr": {
                                "__class__": "BinaryOp",
                                "expr1": {
                                    "__class__": "Name",
                                    "name": "host_load"
                                },
                                "op": ">=",
                                "expr2": {
                                    "__class__": "Integer",
                                    "raw": "4"
                                }
                            },
                            "post_operations": []
                        }
                    ],
                    "enters": [],
                    "durings": [],
                    "exits": [],
                    "during_aspects": [],
                    "is_pseudo": false
                }
            ],
            "transitions": [
                {
                    "__class__": "TransitionDefinition",
                    "from_state": "INIT_STATE",
                    "to_state": "Line",
                    "event_id": null,
                    "condition_expr": null,
                    "post_operations": []
                }
            ],
            "enters": [],
            "durings": [],
            "exits": [],
            "during_aspects": [],
            "is_pseudo": false
        }
    }
},
});
