// Generated by scripts/generate_model_sample_tests.py. Do not edit manually.
import {runPyGeneratedModelCase} from "./support";

runPyGeneratedModelCase({
    name: "dlc6_more.fcstm",
    relativeSourcePath: "dlc6_more.fcstm",
    source: "def int x = 0;\ndef int y = 0;\nstate L1 {\n    enter abstract F1;\n    during before F12 {\n        x = 1;\n    }\n    during after abstract F13;\n    exit F1x ref F1;\n    >> during before ref L21.F1;\n    >> during after ref L22.F1;\n    state L21 {\n        enter F1 {\n            x = 0;\n            y = y + 1;\n        }\n        exit ref /F1x;\n        >> during after ref /F1x;\n    }\n    state L22 {\n        enter ref /F1x;\n        during ref /F1x;\n        during ref F1;\n        exit F1 {\n            x = x + 1;\n            y = 0;\n        }\n        exit ref /F1;\n    }\n    [*] -> L21;\n    L21 -> L22 : if [x > 0];\n}",
    files: undefined,
    entryFile: undefined,
    expected: {
    "defines": {
        "x": {
            "type": "int",
            "init": {
                "type": "Integer",
                "value": 0
            }
        },
        "y": {
            "type": "int",
            "init": {
                "type": "Integer",
                "value": 0
            }
        }
    },
    "root_state": "L1",
    "walk_states": [
        "L1",
        "L1.L21",
        "L1.L22"
    ],
    "all_events": [],
    "all_actions": [
        "L1.F1",
        "L1.F12",
        "L1.F13",
        "L1.F1x",
        "L1.<unnamed>",
        "L1.<unnamed>",
        "L1.L21.F1",
        "L1.L21.<unnamed>",
        "L1.L21.<unnamed>",
        "L1.L22.<unnamed>",
        "L1.L22.<unnamed>",
        "L1.L22.<unnamed>",
        "L1.L22.F1",
        "L1.L22.<unnamed>"
    ],
    "states": {
        "L1": {
            "name": "L1",
            "path": [
                "L1"
            ],
            "parent": null,
            "substates": [
                "L21",
                "L22"
            ],
            "events": {},
            "transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "L21",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "L1"
                },
                {
                    "from_state": "L21",
                    "to_state": "L22",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": ">",
                        "x": {
                            "type": "Variable",
                            "name": "x"
                        },
                        "y": {
                            "type": "Integer",
                            "value": 0
                        }
                    },
                    "effects": [],
                    "parent": "L1"
                }
            ],
            "named_functions": {
                "F1": {
                    "type": "OnStage",
                    "stage": "enter",
                    "aspect": null,
                    "name": "F1",
                    "doc": null,
                    "operations": [],
                    "is_abstract": true,
                    "is_ref": false,
                    "is_aspect": false,
                    "state_path": [
                        "L1",
                        "F1"
                    ],
                    "func_name": "L1.F1",
                    "parent": "L1",
                    "ref_state_path": null,
                    "ref_resolved": false,
                    "ref_target_qualified_name": null
                },
                "F12": {
                    "type": "OnStage",
                    "stage": "during",
                    "aspect": "before",
                    "name": "F12",
                    "doc": null,
                    "operations": [
                        {
                            "type": "Operation",
                            "var_name": "x",
                            "expr": {
                                "type": "Integer",
                                "value": 1
                            }
                        }
                    ],
                    "is_abstract": false,
                    "is_ref": false,
                    "is_aspect": false,
                    "state_path": [
                        "L1",
                        "F12"
                    ],
                    "func_name": "L1.F12",
                    "parent": "L1",
                    "ref_state_path": null,
                    "ref_resolved": false,
                    "ref_target_qualified_name": null
                },
                "F13": {
                    "type": "OnStage",
                    "stage": "during",
                    "aspect": "after",
                    "name": "F13",
                    "doc": null,
                    "operations": [],
                    "is_abstract": true,
                    "is_ref": false,
                    "is_aspect": false,
                    "state_path": [
                        "L1",
                        "F13"
                    ],
                    "func_name": "L1.F13",
                    "parent": "L1",
                    "ref_state_path": null,
                    "ref_resolved": false,
                    "ref_target_qualified_name": null
                },
                "F1x": {
                    "type": "OnStage",
                    "stage": "exit",
                    "aspect": null,
                    "name": "F1x",
                    "doc": null,
                    "operations": [],
                    "is_abstract": false,
                    "is_ref": true,
                    "is_aspect": false,
                    "state_path": [
                        "L1",
                        "F1x"
                    ],
                    "func_name": "L1.F1x",
                    "parent": "L1",
                    "ref_state_path": [
                        "L1",
                        "F1"
                    ],
                    "ref_resolved": true,
                    "ref_target_qualified_name": "L1.F1"
                }
            },
            "on_enters": [
                {
                    "type": "OnStage",
                    "stage": "enter",
                    "aspect": null,
                    "name": "F1",
                    "doc": null,
                    "operations": [],
                    "is_abstract": true,
                    "is_ref": false,
                    "is_aspect": false,
                    "state_path": [
                        "L1",
                        "F1"
                    ],
                    "func_name": "L1.F1",
                    "parent": "L1",
                    "ref_state_path": null,
                    "ref_resolved": false,
                    "ref_target_qualified_name": null
                }
            ],
            "on_durings": [
                {
                    "type": "OnStage",
                    "stage": "during",
                    "aspect": "before",
                    "name": "F12",
                    "doc": null,
                    "operations": [
                        {
                            "type": "Operation",
                            "var_name": "x",
                            "expr": {
                                "type": "Integer",
                                "value": 1
                            }
                        }
                    ],
                    "is_abstract": false,
                    "is_ref": false,
                    "is_aspect": false,
                    "state_path": [
                        "L1",
                        "F12"
                    ],
                    "func_name": "L1.F12",
                    "parent": "L1",
                    "ref_state_path": null,
                    "ref_resolved": false,
                    "ref_target_qualified_name": null
                },
                {
                    "type": "OnStage",
                    "stage": "during",
                    "aspect": "after",
                    "name": "F13",
                    "doc": null,
                    "operations": [],
                    "is_abstract": true,
                    "is_ref": false,
                    "is_aspect": false,
                    "state_path": [
                        "L1",
                        "F13"
                    ],
                    "func_name": "L1.F13",
                    "parent": "L1",
                    "ref_state_path": null,
                    "ref_resolved": false,
                    "ref_target_qualified_name": null
                }
            ],
            "on_exits": [
                {
                    "type": "OnStage",
                    "stage": "exit",
                    "aspect": null,
                    "name": "F1x",
                    "doc": null,
                    "operations": [],
                    "is_abstract": false,
                    "is_ref": true,
                    "is_aspect": false,
                    "state_path": [
                        "L1",
                        "F1x"
                    ],
                    "func_name": "L1.F1x",
                    "parent": "L1",
                    "ref_state_path": [
                        "L1",
                        "F1"
                    ],
                    "ref_resolved": true,
                    "ref_target_qualified_name": "L1.F1"
                }
            ],
            "on_during_aspects": [
                {
                    "type": "OnAspect",
                    "stage": "during",
                    "aspect": "before",
                    "name": null,
                    "doc": null,
                    "operations": [],
                    "is_abstract": false,
                    "is_ref": true,
                    "is_aspect": true,
                    "state_path": [
                        "L1",
                        null
                    ],
                    "func_name": "L1.<unnamed>",
                    "parent": "L1",
                    "ref_state_path": [
                        "L1",
                        "L21",
                        "F1"
                    ],
                    "ref_resolved": true,
                    "ref_target_qualified_name": "L1.L21.F1"
                },
                {
                    "type": "OnAspect",
                    "stage": "during",
                    "aspect": "after",
                    "name": null,
                    "doc": null,
                    "operations": [],
                    "is_abstract": false,
                    "is_ref": true,
                    "is_aspect": true,
                    "state_path": [
                        "L1",
                        null
                    ],
                    "func_name": "L1.<unnamed>",
                    "parent": "L1",
                    "ref_state_path": [
                        "L1",
                        "L22",
                        "F1"
                    ],
                    "ref_resolved": true,
                    "ref_target_qualified_name": "L1.L22.F1"
                }
            ],
            "substate_name_to_id": {
                "L21": 0,
                "L22": 1
            },
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": false,
            "is_root_state": true,
            "is_stoppable": false,
            "abstract_on_enters": [
                "L1.F1"
            ],
            "non_abstract_on_enters": [],
            "abstract_on_durings": [
                "L1.F13"
            ],
            "non_abstract_on_durings": [
                "L1.F12"
            ],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [
                "L1.F1x"
            ],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [
                "L1.<unnamed>",
                "L1.<unnamed>"
            ],
            "init_transitions": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "L21",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "L1"
                }
            ],
            "transitions_from": [
                {
                    "from_state": "L1",
                    "to_state": "EXIT_STATE",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": null
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "L1",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": null
                }
            ],
            "transitions_entering_children": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "L21",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "L1"
                }
            ],
            "transitions_entering_children_simplified": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "L21",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "L1"
                }
            ],
            "list_on_enters": [
                "L1.F1"
            ],
            "list_on_enters_with_ids": [
                [
                    1,
                    "L1.F1"
                ]
            ],
            "list_on_durings": [
                "L1.F12",
                "L1.F13"
            ],
            "list_on_durings_with_ids": [
                [
                    1,
                    "L1.F12"
                ],
                [
                    2,
                    "L1.F13"
                ]
            ],
            "list_on_exits": [
                "L1.F1x"
            ],
            "list_on_exits_with_ids": [
                [
                    1,
                    "L1.F1x"
                ]
            ],
            "list_on_during_aspects": [
                "L1.<unnamed>",
                "L1.<unnamed>"
            ],
            "list_on_during_aspects_with_ids": [
                [
                    1,
                    "L1.<unnamed>"
                ],
                [
                    2,
                    "L1.<unnamed>"
                ]
            ],
            "list_on_during_aspect_recursively": [
                [
                    "L1",
                    "L1.<unnamed>"
                ],
                [
                    "L1",
                    "L1.F12"
                ],
                [
                    "L1",
                    "L1.F13"
                ],
                [
                    "L1",
                    "L1.<unnamed>"
                ]
            ],
            "list_on_during_aspect_recursively_with_ids": [
                [
                    1,
                    "L1",
                    "L1.<unnamed>"
                ],
                [
                    1,
                    "L1",
                    "L1.F12"
                ],
                [
                    2,
                    "L1",
                    "L1.F13"
                ],
                [
                    2,
                    "L1",
                    "L1.<unnamed>"
                ]
            ],
            "walk_states": [
                "L1",
                "L1.L21",
                "L1.L22"
            ]
        },
        "L1.L21": {
            "name": "L21",
            "path": [
                "L1",
                "L21"
            ],
            "parent": "L1",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {
                "F1": {
                    "type": "OnStage",
                    "stage": "enter",
                    "aspect": null,
                    "name": "F1",
                    "doc": null,
                    "operations": [
                        {
                            "type": "Operation",
                            "var_name": "x",
                            "expr": {
                                "type": "Integer",
                                "value": 0
                            }
                        },
                        {
                            "type": "Operation",
                            "var_name": "y",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "y"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        }
                    ],
                    "is_abstract": false,
                    "is_ref": false,
                    "is_aspect": false,
                    "state_path": [
                        "L1",
                        "L21",
                        "F1"
                    ],
                    "func_name": "L1.L21.F1",
                    "parent": "L1.L21",
                    "ref_state_path": null,
                    "ref_resolved": false,
                    "ref_target_qualified_name": null
                }
            },
            "on_enters": [
                {
                    "type": "OnStage",
                    "stage": "enter",
                    "aspect": null,
                    "name": "F1",
                    "doc": null,
                    "operations": [
                        {
                            "type": "Operation",
                            "var_name": "x",
                            "expr": {
                                "type": "Integer",
                                "value": 0
                            }
                        },
                        {
                            "type": "Operation",
                            "var_name": "y",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "y"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        }
                    ],
                    "is_abstract": false,
                    "is_ref": false,
                    "is_aspect": false,
                    "state_path": [
                        "L1",
                        "L21",
                        "F1"
                    ],
                    "func_name": "L1.L21.F1",
                    "parent": "L1.L21",
                    "ref_state_path": null,
                    "ref_resolved": false,
                    "ref_target_qualified_name": null
                }
            ],
            "on_durings": [],
            "on_exits": [
                {
                    "type": "OnStage",
                    "stage": "exit",
                    "aspect": null,
                    "name": null,
                    "doc": null,
                    "operations": [],
                    "is_abstract": false,
                    "is_ref": true,
                    "is_aspect": false,
                    "state_path": [
                        "L1",
                        "L21",
                        null
                    ],
                    "func_name": "L1.L21.<unnamed>",
                    "parent": "L1.L21",
                    "ref_state_path": [
                        "L1",
                        "F1x"
                    ],
                    "ref_resolved": true,
                    "ref_target_qualified_name": "L1.F1x"
                }
            ],
            "on_during_aspects": [
                {
                    "type": "OnAspect",
                    "stage": "during",
                    "aspect": "after",
                    "name": null,
                    "doc": null,
                    "operations": [],
                    "is_abstract": false,
                    "is_ref": true,
                    "is_aspect": true,
                    "state_path": [
                        "L1",
                        "L21",
                        null
                    ],
                    "func_name": "L1.L21.<unnamed>",
                    "parent": "L1.L21",
                    "ref_state_path": [
                        "L1",
                        "F1x"
                    ],
                    "ref_resolved": true,
                    "ref_target_qualified_name": "L1.F1x"
                }
            ],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [
                "L1.L21.F1"
            ],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [
                "L1.L21.<unnamed>"
            ],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [
                "L1.L21.<unnamed>"
            ],
            "init_transitions": [],
            "transitions_from": [
                {
                    "from_state": "L21",
                    "to_state": "L22",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": ">",
                        "x": {
                            "type": "Variable",
                            "name": "x"
                        },
                        "y": {
                            "type": "Integer",
                            "value": 0
                        }
                    },
                    "effects": [],
                    "parent": "L1"
                }
            ],
            "transitions_to": [
                {
                    "from_state": "INIT_STATE",
                    "to_state": "L21",
                    "event": null,
                    "guard": null,
                    "effects": [],
                    "parent": "L1"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [
                "L1.L21.F1"
            ],
            "list_on_enters_with_ids": [
                [
                    1,
                    "L1.L21.F1"
                ]
            ],
            "list_on_durings": [],
            "list_on_durings_with_ids": [],
            "list_on_exits": [
                "L1.L21.<unnamed>"
            ],
            "list_on_exits_with_ids": [
                [
                    1,
                    "L1.L21.<unnamed>"
                ]
            ],
            "list_on_during_aspects": [
                "L1.L21.<unnamed>"
            ],
            "list_on_during_aspects_with_ids": [
                [
                    1,
                    "L1.L21.<unnamed>"
                ]
            ],
            "list_on_during_aspect_recursively": [
                [
                    "L1",
                    "L1.<unnamed>"
                ],
                [
                    "L1.L21",
                    "L1.L21.<unnamed>"
                ],
                [
                    "L1",
                    "L1.<unnamed>"
                ]
            ],
            "list_on_during_aspect_recursively_with_ids": [
                [
                    1,
                    "L1",
                    "L1.<unnamed>"
                ],
                [
                    1,
                    "L1.L21",
                    "L1.L21.<unnamed>"
                ],
                [
                    2,
                    "L1",
                    "L1.<unnamed>"
                ]
            ],
            "walk_states": [
                "L1.L21"
            ]
        },
        "L1.L22": {
            "name": "L22",
            "path": [
                "L1",
                "L22"
            ],
            "parent": "L1",
            "substates": [],
            "events": {},
            "transitions": [],
            "named_functions": {
                "F1": {
                    "type": "OnStage",
                    "stage": "exit",
                    "aspect": null,
                    "name": "F1",
                    "doc": null,
                    "operations": [
                        {
                            "type": "Operation",
                            "var_name": "x",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "x"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        },
                        {
                            "type": "Operation",
                            "var_name": "y",
                            "expr": {
                                "type": "Integer",
                                "value": 0
                            }
                        }
                    ],
                    "is_abstract": false,
                    "is_ref": false,
                    "is_aspect": false,
                    "state_path": [
                        "L1",
                        "L22",
                        "F1"
                    ],
                    "func_name": "L1.L22.F1",
                    "parent": "L1.L22",
                    "ref_state_path": null,
                    "ref_resolved": false,
                    "ref_target_qualified_name": null
                }
            },
            "on_enters": [
                {
                    "type": "OnStage",
                    "stage": "enter",
                    "aspect": null,
                    "name": null,
                    "doc": null,
                    "operations": [],
                    "is_abstract": false,
                    "is_ref": true,
                    "is_aspect": false,
                    "state_path": [
                        "L1",
                        "L22",
                        null
                    ],
                    "func_name": "L1.L22.<unnamed>",
                    "parent": "L1.L22",
                    "ref_state_path": [
                        "L1",
                        "F1x"
                    ],
                    "ref_resolved": true,
                    "ref_target_qualified_name": "L1.F1x"
                }
            ],
            "on_durings": [
                {
                    "type": "OnStage",
                    "stage": "during",
                    "aspect": null,
                    "name": null,
                    "doc": null,
                    "operations": [],
                    "is_abstract": false,
                    "is_ref": true,
                    "is_aspect": false,
                    "state_path": [
                        "L1",
                        "L22",
                        null
                    ],
                    "func_name": "L1.L22.<unnamed>",
                    "parent": "L1.L22",
                    "ref_state_path": [
                        "L1",
                        "F1x"
                    ],
                    "ref_resolved": true,
                    "ref_target_qualified_name": "L1.F1x"
                },
                {
                    "type": "OnStage",
                    "stage": "during",
                    "aspect": null,
                    "name": null,
                    "doc": null,
                    "operations": [],
                    "is_abstract": false,
                    "is_ref": true,
                    "is_aspect": false,
                    "state_path": [
                        "L1",
                        "L22",
                        null
                    ],
                    "func_name": "L1.L22.<unnamed>",
                    "parent": "L1.L22",
                    "ref_state_path": [
                        "L1",
                        "L22",
                        "F1"
                    ],
                    "ref_resolved": true,
                    "ref_target_qualified_name": "L1.L22.F1"
                }
            ],
            "on_exits": [
                {
                    "type": "OnStage",
                    "stage": "exit",
                    "aspect": null,
                    "name": "F1",
                    "doc": null,
                    "operations": [
                        {
                            "type": "Operation",
                            "var_name": "x",
                            "expr": {
                                "type": "BinaryOp",
                                "op": "+",
                                "x": {
                                    "type": "Variable",
                                    "name": "x"
                                },
                                "y": {
                                    "type": "Integer",
                                    "value": 1
                                }
                            }
                        },
                        {
                            "type": "Operation",
                            "var_name": "y",
                            "expr": {
                                "type": "Integer",
                                "value": 0
                            }
                        }
                    ],
                    "is_abstract": false,
                    "is_ref": false,
                    "is_aspect": false,
                    "state_path": [
                        "L1",
                        "L22",
                        "F1"
                    ],
                    "func_name": "L1.L22.F1",
                    "parent": "L1.L22",
                    "ref_state_path": null,
                    "ref_resolved": false,
                    "ref_target_qualified_name": null
                },
                {
                    "type": "OnStage",
                    "stage": "exit",
                    "aspect": null,
                    "name": null,
                    "doc": null,
                    "operations": [],
                    "is_abstract": false,
                    "is_ref": true,
                    "is_aspect": false,
                    "state_path": [
                        "L1",
                        "L22",
                        null
                    ],
                    "func_name": "L1.L22.<unnamed>",
                    "parent": "L1.L22",
                    "ref_state_path": [
                        "L1",
                        "F1"
                    ],
                    "ref_resolved": true,
                    "ref_target_qualified_name": "L1.F1"
                }
            ],
            "on_during_aspects": [],
            "substate_name_to_id": {},
            "extra_name": null,
            "is_pseudo": false,
            "is_leaf_state": true,
            "is_root_state": false,
            "is_stoppable": true,
            "abstract_on_enters": [],
            "non_abstract_on_enters": [
                "L1.L22.<unnamed>"
            ],
            "abstract_on_durings": [],
            "non_abstract_on_durings": [
                "L1.L22.<unnamed>",
                "L1.L22.<unnamed>"
            ],
            "abstract_on_exits": [],
            "non_abstract_on_exits": [
                "L1.L22.F1",
                "L1.L22.<unnamed>"
            ],
            "abstract_on_during_aspects": [],
            "non_abstract_on_during_aspects": [],
            "init_transitions": [],
            "transitions_from": [],
            "transitions_to": [
                {
                    "from_state": "L21",
                    "to_state": "L22",
                    "event": null,
                    "guard": {
                        "type": "BinaryOp",
                        "op": ">",
                        "x": {
                            "type": "Variable",
                            "name": "x"
                        },
                        "y": {
                            "type": "Integer",
                            "value": 0
                        }
                    },
                    "effects": [],
                    "parent": "L1"
                }
            ],
            "transitions_entering_children": [],
            "transitions_entering_children_simplified": [
                null
            ],
            "list_on_enters": [
                "L1.L22.<unnamed>"
            ],
            "list_on_enters_with_ids": [
                [
                    1,
                    "L1.L22.<unnamed>"
                ]
            ],
            "list_on_durings": [
                "L1.L22.<unnamed>",
                "L1.L22.<unnamed>"
            ],
            "list_on_durings_with_ids": [
                [
                    1,
                    "L1.L22.<unnamed>"
                ],
                [
                    2,
                    "L1.L22.<unnamed>"
                ]
            ],
            "list_on_exits": [
                "L1.L22.F1",
                "L1.L22.<unnamed>"
            ],
            "list_on_exits_with_ids": [
                [
                    1,
                    "L1.L22.F1"
                ],
                [
                    2,
                    "L1.L22.<unnamed>"
                ]
            ],
            "list_on_during_aspects": [],
            "list_on_during_aspects_with_ids": [],
            "list_on_during_aspect_recursively": [
                [
                    "L1",
                    "L1.<unnamed>"
                ],
                [
                    "L1.L22",
                    "L1.L22.<unnamed>"
                ],
                [
                    "L1.L22",
                    "L1.L22.<unnamed>"
                ],
                [
                    "L1",
                    "L1.<unnamed>"
                ]
            ],
            "list_on_during_aspect_recursively_with_ids": [
                [
                    1,
                    "L1",
                    "L1.<unnamed>"
                ],
                [
                    1,
                    "L1.L22",
                    "L1.L22.<unnamed>"
                ],
                [
                    2,
                    "L1.L22",
                    "L1.L22.<unnamed>"
                ],
                [
                    2,
                    "L1",
                    "L1.<unnamed>"
                ]
            ],
            "walk_states": [
                "L1.L22"
            ]
        }
    },
    "ast": {
        "__class__": "StateMachineDSLProgram",
        "definitions": [
            {
                "__class__": "DefAssignment",
                "name": "x",
                "type": "int",
                "expr": {
                    "__class__": "Integer",
                    "raw": "0"
                }
            },
            {
                "__class__": "DefAssignment",
                "name": "y",
                "type": "int",
                "expr": {
                    "__class__": "Integer",
                    "raw": "0"
                }
            }
        ],
        "root_state": {
            "__class__": "StateDefinition",
            "name": "L1",
            "extra_name": null,
            "events": [],
            "substates": [
                {
                    "__class__": "StateDefinition",
                    "name": "L21",
                    "extra_name": null,
                    "events": [],
                    "substates": [],
                    "transitions": [],
                    "enters": [
                        {
                            "__class__": "EnterOperations",
                            "name": "F1",
                            "aspect": null,
                            "doc": null,
                            "operations": [
                                {
                                    "__class__": "OperationAssignment",
                                    "name": "x",
                                    "expr": {
                                        "__class__": "Integer",
                                        "raw": "0"
                                    }
                                },
                                {
                                    "__class__": "OperationAssignment",
                                    "name": "y",
                                    "expr": {
                                        "__class__": "BinaryOp",
                                        "expr1": {
                                            "__class__": "Name",
                                            "name": "y"
                                        },
                                        "op": "+",
                                        "expr2": {
                                            "__class__": "Integer",
                                            "raw": "1"
                                        }
                                    }
                                }
                            ],
                            "ref": null
                        }
                    ],
                    "durings": [],
                    "exits": [
                        {
                            "__class__": "ExitRefFunction",
                            "name": null,
                            "aspect": null,
                            "doc": null,
                            "operations": null,
                            "ref": {
                                "__class__": "ChainID",
                                "path": [
                                    "F1x"
                                ],
                                "is_absolute": true
                            }
                        }
                    ],
                    "during_aspects": [
                        {
                            "__class__": "DuringAspectRefFunction",
                            "name": null,
                            "aspect": "after",
                            "doc": null,
                            "operations": null,
                            "ref": {
                                "__class__": "ChainID",
                                "path": [
                                    "F1x"
                                ],
                                "is_absolute": true
                            }
                        }
                    ],
                    "is_pseudo": false
                },
                {
                    "__class__": "StateDefinition",
                    "name": "L22",
                    "extra_name": null,
                    "events": [],
                    "substates": [],
                    "transitions": [],
                    "enters": [
                        {
                            "__class__": "EnterRefFunction",
                            "name": null,
                            "aspect": null,
                            "doc": null,
                            "operations": null,
                            "ref": {
                                "__class__": "ChainID",
                                "path": [
                                    "F1x"
                                ],
                                "is_absolute": true
                            }
                        }
                    ],
                    "durings": [
                        {
                            "__class__": "DuringRefFunction",
                            "name": null,
                            "aspect": null,
                            "doc": null,
                            "operations": null,
                            "ref": {
                                "__class__": "ChainID",
                                "path": [
                                    "F1x"
                                ],
                                "is_absolute": true
                            }
                        },
                        {
                            "__class__": "DuringRefFunction",
                            "name": null,
                            "aspect": null,
                            "doc": null,
                            "operations": null,
                            "ref": {
                                "__class__": "ChainID",
                                "path": [
                                    "F1"
                                ],
                                "is_absolute": false
                            }
                        }
                    ],
                    "exits": [
                        {
                            "__class__": "ExitOperations",
                            "name": "F1",
                            "aspect": null,
                            "doc": null,
                            "operations": [
                                {
                                    "__class__": "OperationAssignment",
                                    "name": "x",
                                    "expr": {
                                        "__class__": "BinaryOp",
                                        "expr1": {
                                            "__class__": "Name",
                                            "name": "x"
                                        },
                                        "op": "+",
                                        "expr2": {
                                            "__class__": "Integer",
                                            "raw": "1"
                                        }
                                    }
                                },
                                {
                                    "__class__": "OperationAssignment",
                                    "name": "y",
                                    "expr": {
                                        "__class__": "Integer",
                                        "raw": "0"
                                    }
                                }
                            ],
                            "ref": null
                        },
                        {
                            "__class__": "ExitRefFunction",
                            "name": null,
                            "aspect": null,
                            "doc": null,
                            "operations": null,
                            "ref": {
                                "__class__": "ChainID",
                                "path": [
                                    "F1"
                                ],
                                "is_absolute": true
                            }
                        }
                    ],
                    "during_aspects": [],
                    "is_pseudo": false
                }
            ],
            "transitions": [
                {
                    "__class__": "TransitionDefinition",
                    "from_state": "INIT_STATE",
                    "to_state": "L21",
                    "event_id": null,
                    "condition_expr": null,
                    "post_operations": []
                },
                {
                    "__class__": "TransitionDefinition",
                    "from_state": "L21",
                    "to_state": "L22",
                    "event_id": null,
                    "condition_expr": {
                        "__class__": "BinaryOp",
                        "expr1": {
                            "__class__": "Name",
                            "name": "x"
                        },
                        "op": ">",
                        "expr2": {
                            "__class__": "Integer",
                            "raw": "0"
                        }
                    },
                    "post_operations": []
                }
            ],
            "enters": [
                {
                    "__class__": "EnterAbstractFunction",
                    "name": "F1",
                    "aspect": null,
                    "doc": null,
                    "operations": null,
                    "ref": null
                }
            ],
            "durings": [
                {
                    "__class__": "DuringOperations",
                    "name": "F12",
                    "aspect": "before",
                    "doc": null,
                    "operations": [
                        {
                            "__class__": "OperationAssignment",
                            "name": "x",
                            "expr": {
                                "__class__": "Integer",
                                "raw": "1"
                            }
                        }
                    ],
                    "ref": null
                },
                {
                    "__class__": "DuringAbstractFunction",
                    "name": "F13",
                    "aspect": "after",
                    "doc": null,
                    "operations": null,
                    "ref": null
                }
            ],
            "exits": [
                {
                    "__class__": "ExitRefFunction",
                    "name": "F1x",
                    "aspect": null,
                    "doc": null,
                    "operations": null,
                    "ref": {
                        "__class__": "ChainID",
                        "path": [
                            "F1"
                        ],
                        "is_absolute": false
                    }
                }
            ],
            "during_aspects": [
                {
                    "__class__": "DuringAspectRefFunction",
                    "name": null,
                    "aspect": "before",
                    "doc": null,
                    "operations": null,
                    "ref": {
                        "__class__": "ChainID",
                        "path": [
                            "L21",
                            "F1"
                        ],
                        "is_absolute": false
                    }
                },
                {
                    "__class__": "DuringAspectRefFunction",
                    "name": null,
                    "aspect": "after",
                    "doc": null,
                    "operations": null,
                    "ref": {
                        "__class__": "ChainID",
                        "path": [
                            "L22",
                            "F1"
                        ],
                        "is_absolute": false
                    }
                }
            ],
            "is_pseudo": false
        }
    }
},
});
