"""
Build-produced resources for the offline diagram renderer.

The package deliberately contains no renderer implementation. JavaScript,
WASM, font, manifest, and license assets are regenerated by
``make build_assets`` and are ignored by git; this module exists so normal
Python packaging includes the generated directory when it is present.

The public resource contract is:

* ``renderer.js`` - ES2017 shared ELK/SVG/resvg bridge;
* ``resvg.wasm`` - pinned legacy-compatible raster/vector backend;
* ``manifest.json`` - source, hash, and size evidence;
* ``fonts/`` plus the tracked notice and license files - deterministic
  provenance resources.

The package does not expose the future ``StateMachine.diagram`` API. That
API belongs to the continuation Python surface described by PR #383.
"""
