#!/usr/bin/env python
"""
Generate optimized PyInstaller spec file with all necessary resource files
"""
import argparse
import sys
from pathlib import Path


EXCLUDED_MODULES = [
    # GUI, data-science, and notebook stacks that are not used by the CLI.
    'tkinter',
    'matplotlib',
    'numpy',
    'pandas',
    'scipy',
    'IPython',
    'jupyter',
    'notebook',
    # Test and documentation helpers that should never ship in the standalone build.
    'pytest',
    'unittest',
    'doctest',
    'pydoc',
    # Packaging and installer tooling that is only present in the build environment.
    'PyInstaller',
    '_pyinstaller_hooks_contrib',
    'altgraph',
    'macholib',
    'pefile',
    'win32ctypes',
    'distutils',
    'setuptools',
    'pip',
    # Icon generation dependencies observed in Release Test environments.
    'PIL',
    'cairosvg',
    'cairocffi',
    'cffi',
    '_cffi_backend',
    'cssselect2',
    'defusedxml',
    'tinycss2',
    'webencodings',
    # Miscellaneous stdlib/test helpers that are not required by the CLI runtime.
    'xmlrpc',
    'http.server',
    '_pytest',
    'py',
]


def collect_datas(bundle_icon=None):
    """Collect data files that need to be packaged"""
    datas = []

    # Try to collect resources from tools.resources
    try:
        from tools.resources import get_resource_files
        for src_file, dst_dir in get_resource_files():
            datas.append((src_file, dst_dir))
    except Exception as e:
        print(f"Warning: Could not collect resources from tools.resources: {e}", file=sys.stderr)

    if bundle_icon:
        bundle_icon_path = Path(bundle_icon)
        if bundle_icon_path.exists():
            datas.append((str(bundle_icon_path), 'icons'))
        else:
            print(f"Warning: Could not find bundled icon: {bundle_icon_path}", file=sys.stderr)

    return datas


def resolve_executable_icon(icon_dir):
    """Resolve the native executable icon path for the current platform."""
    icon_root = Path(icon_dir)
    if sys.platform.startswith('win'):
        icon_path = icon_root / 'pyfcstm.ico'
    elif sys.platform == 'darwin':
        icon_path = icon_root / 'pyfcstm.icns'
    else:
        return None

    if icon_path.exists():
        return str(icon_path)

    print(f"Warning: Could not find executable icon: {icon_path}", file=sys.stderr)
    return None


def generate_spec(icon_dir='build/icons'):
    """Generate spec file content"""
    icon_root = Path(icon_dir)
    datas = collect_datas(bundle_icon=icon_root / 'pyfcstm.png')
    executable_icon = resolve_executable_icon(icon_root)

    spec_content = f'''# -*- mode: python ; coding: utf-8 -*-

# Optimized configuration: reduce size, improve startup speed
# This file is automatically generated by tools/generate_spec.py

a = Analysis(
    ['pyfcstm_cli.py'],
    pathex=[],
    binaries=[],
    datas={datas!r},
    hiddenimports=[],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    # Exclude unnecessary modules to reduce size
    excludes={EXCLUDED_MODULES!r},
    noarchive=False,
)

# Use compressed PYZ archive
pyz = PYZ(
    a.pure,
    a.zipped_data,
    cipher=None
)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='pyfcstm',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,              # Enable symbol stripping to reduce size
    upx=True,                # Enable UPX compression
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon={executable_icon!r},
)
'''

    return spec_content, len(datas)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Generate optimized PyInstaller spec file with all necessary resource files'
    )
    parser.add_argument(
        '-o', '--output',
        default='pyfcstm.spec',
        help='Output spec file path (default: pyfcstm.spec)'
    )
    parser.add_argument(
        '--icon-dir',
        default='build/icons',
        help='Generated application icon directory (default: build/icons)'
    )
    args = parser.parse_args()

    spec_content, data_count = generate_spec(icon_dir=args.icon_dir)

    # Write spec file
    with open(args.output, 'w', encoding='utf-8') as f:
        f.write(spec_content)

    print(f"Generated {args.output} with {data_count} data files")
