#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Capture git state + build time, emit ``pyfcstm/_build_info.py``.

Designed to be:
* **Idempotent** - safe to call multiple times in a single make run.
* **Defensive**  - if git is missing, the source tree is not a git
  checkout, or any subprocess fails, the helper still emits a valid
  ``_build_info.py`` (with placeholder values). Build pipelines must
  not be allowed to break because of this helper.

Invocation::

    python -m tools.write_build_info
"""
from __future__ import annotations

import datetime
import platform
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "pyfcstm" / "config" / "build_info.py"


def _git(*args: str, default: str = "") -> str:
    """Run ``git <args>`` from the repo root and return stdout, or
    ``default`` on any failure (missing binary, non-zero exit, timeout,
    permission error, ...)."""
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=str(ROOT),
            capture_output=True,
            text=True,
            timeout=15,
        )
    except Exception:
        return default
    if result.returncode != 0:
        return default
    return (result.stdout or "").strip()


def _gather():
    commit = _git("rev-parse", "HEAD") or None
    short = commit[:12] if commit else None
    branch = _git("rev-parse", "--abbrev-ref", "HEAD") or None
    status = _git("status", "--porcelain")
    dirty = bool(status)
    dirty_files = tuple(
        line[3:] if len(line) > 3 else line
        for line in status.splitlines()
    ) if status else ()
    return {
        "BUILD_COMMIT": commit,
        "BUILD_COMMIT_SHORT": short,
        "BUILD_BRANCH": branch,
        "BUILD_TIME_UTC": datetime.datetime.utcnow().isoformat(timespec="seconds") + "Z",
        "BUILD_DIRTY": dirty if commit is not None else None,
        "BUILD_DIRTY_FILES": dirty_files,
        "BUILD_HOST": platform.node() or None,
    }


_HEADER = '''"""
Build-time metadata baked into the pyfcstm package.

This file is regenerated by ``tools/write_build_info.py`` whenever
``make build`` or ``make package`` is invoked. Do **not** edit by hand;
your changes will be overwritten on the next build. Values fall back to
``None`` when the build was not performed via the Makefile.

The values are read by :mod:`pyfcstm.diagnostics` to surface "which
commit / when / dirty?" facts even when the running artefact is a
frozen exe with no ``.git/`` directory available at runtime.
"""

from __future__ import annotations
'''


def main() -> int:
    info = _gather()
    body_lines = [_HEADER, ""]
    for key, value in info.items():
        body_lines.append("{} = {!r}".format(key, value))
    body = "\n".join(body_lines).rstrip() + "\n"
    TARGET.write_text(body, encoding="utf-8")
    print("[build-info] wrote {} ({} entries, dirty={})".format(
        TARGET.relative_to(ROOT), len(info), info.get("BUILD_DIRTY"),
    ))
    return 0


if __name__ == "__main__":
    sys.exit(main())
