@startuml
hide empty description

skinparam state {
  BackgroundColor<<pseudo>> LightGray
  BackgroundColor<<composite>> LightBlue
  BorderColor<<pseudo>> Gray
  FontStyle<<pseudo>> italic
}

legend right
|= Variable |= Type |= Initial Value |
| counter | int | 0 |
| error_count | int | 0 |
endlegend

state "System (System)" as system <<composite>> {
    state "Idle (System.Idle)" as system__idle
    system__idle : enter {\n    counter = 0;\n}
    state "Active (System.Active)" as system__active <<composite>> {
        state "Processing (System.Active.Processing)" as system__active__processing
        system__active__processing : during {\n    counter = counter + 10;\n}
        state "Waiting (System.Active.Waiting)" as system__active__waiting
        system__active__processing -[#4E79A7]-> [*] : /FatalError
        system__active__waiting -[#4E79A7]-> [*] : /FatalError
        [*] --> system__active__processing
        system__active__processing --> system__active__waiting : Processing.Pause
        system__active__waiting --> system__active__processing : Waiting.Resume
    }
    system__active : during before {\n    counter = counter + 1;\n}
    state "Error (System.Error)" as system__error
    system__error : enter {\n    error_count = error_count + 1;\n}
    system__idle -[#4E79A7]-> system__error : FatalError
    system__active -[#4E79A7]-> system__error : FatalError
    system__error -[#4E79A7]-> system__error : FatalError
    [*] --> system__idle
    system__idle --> system__active : Idle.Start
    system__active --> system__idle : Active.Stop
    note on link
    effect {
        counter = 0;
    }
    end note
    system__active --> system__error : counter > 100
    system__error --> system__idle : error_count < 3
}
system : >> during before abstract GlobalMonitor;
[*] --> system
system --> [*]
@enduml